function Summary = Diag_Visualize_Step05_EtaZero_Reconstruction_20251222()
%DIAG_VISUALIZE_STEP05_ETAZERO_RECONSTRUCTION_20251222
% Visual comparison of official NoEta and legacy fixed-eta-zero Step05 fits.
%
% The fixed-eta-zero result is not expected to reproduce official NoEta,
% because it is generated by the archived fixed-eta branch with different
% window timing and phase-safe expansion settings. This diagnostic makes the
% waveform-level mismatch visible.

clc; close all;

cfg = BTTProjectConfig_20251222();
case_name = cfg.dynamic_cases{1};

noeta_file = fullfile(cfg.output_root, ...
    'step05_single_sync_direct_template', case_name, ...
    'Result_Step05_FoundationMainPulseAdaptiveNoEtaVoltageDecision_B1_S123_20251222.mat');
eta_zero_file = fullfile(cfg.output_root, ...
    'step05_single_sync_direct_template_etadiag_zero', case_name, ...
    'Result_Step05_FoundationMainPulseAdaptiveFixedJointEta_B1_S123_20251222.mat');

if ~isfile(noeta_file)
    error('Official NoEta result not found: %s', noeta_file);
end
if ~isfile(eta_zero_file)
    error(['Eta-zero diagnostic result not found: %s\n' ...
        'Run Diag_Step05_FixedEtaScaleMatrix_20251222 first.'], eta_zero_file);
end

loaded = load(noeta_file, 'Result');
NoEta = loaded.Result;
loaded = load(eta_zero_file, 'Result');
EtaZero = loaded.Result;

out_dir = fullfile(cfg.output_root, 'diagnostics', ...
    'step05_fixed_eta_scale_matrix_20251222', 'figures');
if exist(out_dir, 'dir') ~= 7
    mkdir(out_dir);
end

max_windows = min([2, numel(NoEta.WindowResult), numel(EtaZero.WindowResult)]);
FigureFiles = strings(max_windows, 1);

for iw = 1:max_windows
    FigureFiles(iw) = plot_window_compare_local(NoEta, EtaZero, iw, out_dir);
end

SettingsTable = make_settings_table_local(NoEta, EtaZero);
WindowTable = make_window_table_local(NoEta, EtaZero, max_windows);

settings_csv = fullfile(out_dir, ...
    'Step05_NoEta_vs_EtaZero_Settings_20251222.csv');
window_csv = fullfile(out_dir, ...
    'Step05_NoEta_vs_EtaZero_WindowCompare_20251222.csv');
writetable(SettingsTable, settings_csv);
writetable(WindowTable, window_csv);

Summary = struct();
Summary.NoEtaFile = noeta_file;
Summary.EtaZeroFile = eta_zero_file;
Summary.OutputDir = out_dir;
Summary.FigureFiles = FigureFiles;
Summary.SettingsTable = SettingsTable;
Summary.WindowTable = WindowTable;
Summary.SettingsCSV = settings_csv;
Summary.WindowCSV = window_csv;

summary_mat = fullfile(out_dir, ...
    'Step05_NoEta_vs_EtaZero_ReconstructionSummary_20251222.mat');
save(summary_mat, 'Summary');

fprintf('\n=== Step05 NoEta vs fixed-eta-zero reconstruction diagnostic ===\n');
disp(SettingsTable);
disp(WindowTable);
fprintf('Figures:\n');
for i = 1:numel(FigureFiles)
    fprintf('  %s\n', FigureFiles(i));
end
end


function fig_file = plot_window_compare_local(NoEta, EtaZero, iw, out_dir)
sensors = NoEta.SensorIDs(:).';
fig = figure('Color', 'w', 'Position', [80 80 1700 1050], ...
    'Visible', 'off', 'NumberTitle', 'off', ...
    'Name', sprintf('Step05 W%d NoEta vs eta-zero reconstruction', iw));
tiledlayout(fig, numel(sensors), 4, ...
    'TileSpacing', 'compact', 'Padding', 'compact');

for is = 1:numel(sensors)
    sid = sensors(is);
    plot_branch_time_local(nexttile, NoEta, iw, sid, ...
        'Official NoEta: observed vs predicted');
    plot_branch_residual_local(nexttile, NoEta, iw, sid, ...
        'Official NoEta residual');
    plot_branch_time_local(nexttile, EtaZero, iw, sid, ...
        'Legacy fixed-eta-zero: observed vs predicted');
    plot_branch_residual_local(nexttile, EtaZero, iw, sid, ...
        'Legacy fixed-eta-zero residual');
end

rn = NoEta.WindowResult(iw).Result;
rz = EtaZero.WindowResult(iw).Result;
tn = NoEta.WindowResult(iw).time_window_s;
tz = EtaZero.WindowResult(iw).time_window_s;

sgtitle(sprintf(['W%d waveform reconstruction | NoEta EO%d A=%.3f dx=%.3f RMSE=%.4f, ' ...
    't=[%.4f %.4f] | eta0 EO%d A=%.3f dx=%.3f RMSE=%.4f, t=[%.4f %.4f]'], ...
    iw, rn.EO_id, rn.A_id, rn.dx_c_id, rn.weighted_voltage_rmse, ...
    tn(1), tn(2), rz.EO_id, rz.A_id, rz.dx_c_id, rz.weighted_voltage_rmse, ...
    tz(1), tz(2)), 'Interpreter', 'none');

fig_file = fullfile(out_dir, sprintf( ...
    'Step05_W%d_NoEta_vs_FixedEtaZero_Reconstruction.png', iw));
exportgraphics(fig, fig_file, 'Resolution', 220);
savefig(fig, strrep(fig_file, '.png', '.fig'));
close(fig);
end


function plot_branch_time_local(ax, Result, iw, sid, title_text)
WR = Result.WindowResult(iw);
R = WR.Result.ReconstructionPreview;
m = R.sensor_id == sid & isfinite(R.t) & isfinite(R.v_obs) & isfinite(R.v_pred);
hold(ax, 'on'); grid(ax, 'on'); box(ax, 'on');
if any(m)
    t_ms = (R.t(m) - min(R.t(m))) * 1000;
    [t_ms, ord] = sort(t_ms);
    v_obs = R.v_obs(m);
    v_pred = R.v_pred(m);
    v_obs = v_obs(ord);
    v_pred = v_pred(ord);
    plot(ax, t_ms, v_obs, '.', 'Color', [0.62 0.62 0.62], ...
        'MarkerSize', 3, 'DisplayName', 'observed');
    plot(ax, t_ms, v_pred, '.', 'Color', [0.00 0.32 0.70], ...
        'MarkerSize', 4, 'DisplayName', 'predicted');
end
ylabel(ax, sprintf('CH%d V', sid));
xlabel(ax, 'relative time (ms)');
title(ax, title_text, 'Interpreter', 'none');
legend(ax, 'Location', 'best');
end


function plot_branch_residual_local(ax, Result, iw, sid, title_text)
WR = Result.WindowResult(iw);
R = WR.Result.ReconstructionPreview;
m = R.sensor_id == sid & isfinite(R.t) & isfinite(R.v_obs) & isfinite(R.v_pred);
hold(ax, 'on'); grid(ax, 'on'); box(ax, 'on');
if any(m)
    t_ms = (R.t(m) - min(R.t(m))) * 1000;
    [t_ms, ord] = sort(t_ms);
    res = R.v_obs(m) - R.v_pred(m);
    res = res(ord);
    plot(ax, t_ms, res, '.', 'Color', [0.78 0.25 0.10], ...
        'MarkerSize', 4);
end
yline(ax, 0, 'k-');
ylabel(ax, sprintf('CH%d residual V', sid));
xlabel(ax, 'relative time (ms)');
title(ax, title_text, 'Interpreter', 'none');
end


function T = make_settings_table_local(NoEta, EtaZero)
sn = NoEta.AnalysisSettings;
sz = EtaZero.AnalysisSettings;
names = ["analysis_start_time_s"; "target_laps"; "window_laps"; ...
    "core_mask_mode"; "query_guard_mode"; "phase_safe_expansion"; ...
    "active_eta_model"; "method_name"];
official = strings(numel(names), 1);
eta_zero = strings(numel(names), 1);
for i = 1:numel(names)
    official(i) = field_text_local(sn, names(i));
    eta_zero(i) = field_text_local(sz, names(i));
end
T = table(names, official, eta_zero, ...
    'VariableNames', {'setting', 'official_noeta', 'fixed_eta_zero'});
end


function T = make_window_table_local(NoEta, EtaZero, max_windows)
rows = repmat(struct( ...
    'window_id', NaN, ...
    'noeta_time_start_s', NaN, ...
    'noeta_time_end_s', NaN, ...
    'noeta_EO', NaN, ...
    'noeta_A_mm', NaN, ...
    'noeta_dx_c_mm', NaN, ...
    'noeta_rmse_v', NaN, ...
    'eta0_time_start_s', NaN, ...
    'eta0_time_end_s', NaN, ...
    'eta0_EO', NaN, ...
    'eta0_A_mm', NaN, ...
    'eta0_dx_c_mm', NaN, ...
    'eta0_rmse_v', NaN), max_windows, 1);

for iw = 1:max_windows
    rn = NoEta.WindowResult(iw).Result;
    rz = EtaZero.WindowResult(iw).Result;
    tn = NoEta.WindowResult(iw).time_window_s;
    tz = EtaZero.WindowResult(iw).time_window_s;
    rows(iw).window_id = iw;
    rows(iw).noeta_time_start_s = tn(1);
    rows(iw).noeta_time_end_s = tn(2);
    rows(iw).noeta_EO = rn.EO_id;
    rows(iw).noeta_A_mm = rn.A_id;
    rows(iw).noeta_dx_c_mm = rn.dx_c_id;
    rows(iw).noeta_rmse_v = rn.weighted_voltage_rmse;
    rows(iw).eta0_time_start_s = tz(1);
    rows(iw).eta0_time_end_s = tz(2);
    rows(iw).eta0_EO = rz.EO_id;
    rows(iw).eta0_A_mm = rz.A_id;
    rows(iw).eta0_dx_c_mm = rz.dx_c_id;
    rows(iw).eta0_rmse_v = rz.weighted_voltage_rmse;
end

T = struct2table(rows);
end


function txt = field_text_local(s, name)
name = char(name);
if ~isstruct(s) || ~isfield(s, name)
    txt = "";
    return;
end
v = s.(name);
if ischar(v) || isstring(v)
    txt = string(v);
elseif isnumeric(v) || islogical(v)
    txt = string(mat2str(v));
else
    txt = string(class(v));
end
end
