%% 01: build physical-blade BTT displacement for 20241106
% This script uses the 900 rpm data as the no-vibration timing reference.
% It does not reuse the old 20250527/20251222 OPR channel geometry.
%
% For each probe:
%   1. Convert each blade-passing time to a normalized OPR phase in one rev.
%   2. Use the low-speed 900 rpm run to learn six reference phases.
%   3. Convert high-speed phase deviations to circumferential displacement:
%
%        x_mm = r_tip_mm * 2*pi * wrap(alpha_high - alpha_ref)
%
%   4. Replace the probe-local phase-slot number with the physical blade_id
%      generated by the Foundation Step02 fingerprint matcher.

clear; clc; close all;

packageRoot = fileparts(mfilename('fullpath'));
addpath(packageRoot, fullfile(packageRoot, 'functions', 'foundation'), ...
    fullfile(packageRoot, 'functions', 'preparation'), ...
    fullfile(packageRoot, 'functions', 'gap_aware'), ...
    fullfile(packageRoot, 'functions', 'utilities'));

%% 1. Simple settings
dataRoot = 'D:\博士-国科\试验台数据\新试验\20241106_2';
lowDir = fullfile(dataRoot, '900');
highDir = fullfile(dataRoot, '3000_3150');

sensorIds = [2 3 4 5 6 7];
bladeCount = 6;
sampleRateHz = 5e6;
rTipMm = 65.0;
thisDir = fileparts(mfilename('fullpath'));
packageCfg = Config_20241106();
if packageCfg.preparation.rebuildFromRaw
    Run_Script_Isolated_20241106(fullfile(packageCfg.paths.preparation, ...
        'Step01_Build_LowSpeed_Reference_20241106.m'));
    Run_Script_Isolated_20241106(fullfile(packageCfg.paths.preparation, ...
        'Step02_Extract_Dynamic_BTT_20241106.m'));
    Run_Script_Isolated_20241106(fullfile(packageCfg.paths.foundation, ...
        'Step03_Build_Dynamic_Observation_Bundle_20241106.m'));
    Run_Script_Isolated_20241106(fullfile(packageCfg.paths.preparation, ...
        'Step04_Build_LowSpeed_OPRCenterStd_Template_20241106.m'));
else
    Prepare_Bundled_Inputs_20241106(packageCfg);
end
dataRoot = packageCfg.paths.rawDatasetRoot;
lowDir = fullfile(dataRoot, '900');
highDir = fullfile(dataRoot, '3000_3150');
outDir = packageCfg.paths.gapRuntime;
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

targetPhysicalBlade = 4;
targetLowSpeedSlot = 1;
foundationStep02Dir = fullfile(packageCfg.paths.preparedFoundation, ...
    'step02_dynamic_btt', '3000_3150');

%% 2. Load low-speed and high-speed timing
low = load_case_timing_local(lowDir, sensorIds, sampleRateHz);
high = load_case_timing_local(highDir, sensorIds, sampleRateHz);

%% 3. Learn low-speed reference phases
phaseRef = learn_low_speed_phase_reference_local(low, sensorIds, bladeCount);

%% 4. Load Foundation physical blade labels and displacement directly
[highDisp, bladeNumbering] = load_foundation_physical_displacement_local( ...
    foundationStep02Dir, sensorIds, bladeCount);
lowCheck = build_displacement_case_local(low, phaseRef, sensorIds, bladeCount, rTipMm);

%% 5. Print diagnostics
fprintf('\n=== Step02 20241106 simple BTT displacement ===\n');
fprintf('Reference run: %s\n', lowDir);
fprintf('Dynamic run  : %s\n', highDir);
fprintf('Sensors: %s, physical blades: 1-%d, r_tip = %.2f mm\n', ...
    mat2str(sensorIds), bladeCount, rTipMm);
fprintf('Displacement sign follows x = R*2*pi*(phase - low-speed reference phase).\n');
fprintf('High-speed blade IDs come from Foundation jilublade(:,4).\n\n');

print_phase_reference_local(phaseRef, sensorIds, bladeCount);
print_displacement_summary_local('Low-speed self-check', lowCheck, sensorIds, bladeCount);
print_displacement_summary_local('High-speed result', highDisp, sensorIds, bladeCount);

%% 6. Figures
plot_phase_reference_local(phaseRef, sensorIds, bladeCount);
plot_speed_and_target_blade_local(high, highDisp, sensorIds, targetPhysicalBlade);
plot_sensor_slot_overview_local(highDisp, sensorIds, bladeCount);
plot_low_speed_self_check_local(lowCheck, sensorIds, targetLowSpeedSlot);

%% 7. Save reusable BTT displacement result for later steps
matFile = fullfile(outDir, 'Step02_BTT_Displacement_20241106.mat');
save(matFile, 'highDisp', 'lowCheck', 'phaseRef', 'sensorIds', ...
    'bladeCount', 'bladeNumbering', 'sampleRateHz', 'rTipMm', 'lowDir', 'highDir');
fprintf('\nSaved reusable Step02 BTT result:\n  %s\n', matFile);

fprintf('\nDone. Figures are open in MATLAB.\n');

%% Local functions
function C = load_case_timing_local(caseDir, sensorIds, sampleRateHz)
C.caseDir = caseDir;
C.opr = load_opr_local(caseDir, sampleRateHz);
C.probe = load_probe_set_local(caseDir, sensorIds);
C.speedTime = C.opr.tCenter(1:end-1);
C.rpm = 60 ./ diff(C.opr.tCenter);
end

function opr = load_opr_local(caseDir, sampleRateHz)
oprFile = fullfile(caseDir, 'jiluOPR.mat');
if exist(oprFile, 'file') ~= 2
    error('Missing OPR file: %s', oprFile);
end

S = load(oprFile, 'jiluOPR');
raw = S.jiluOPR;
opr.file = oprFile;
opr.raw = raw;
opr.tStart = raw(:, 1) / sampleRateHz;
opr.tEnd = raw(:, 2) / sampleRateHz;
opr.tCenter = mean(raw(:, 1:2), 2) / sampleRateHz;
end

function probes = load_probe_set_local(caseDir, sensorIds)
emptyProbe = struct('sensorId', NaN, 'file', '', 'data', [], 'tCenter', []);
probes = repmat(emptyProbe, numel(sensorIds), 1);

for i = 1:numel(sensorIds)
    sid = sensorIds(i);
    probeFile = find_probe_file_local(caseDir, sid);
    if isempty(probeFile)
        warning('Probe %d file not found in %s.', sid, caseDir);
        probes(i).sensorId = sid;
        continue;
    end

    S = load(probeFile, 'jilublade');
    probes(i).sensorId = sid;
    probes(i).file = probeFile;
    probes(i).data = S.jilublade;
    probes(i).tCenter = S.jilublade(:, 3);
end
end

function probeFile = find_probe_file_local(caseDir, sensorId)
preferred = fullfile(caseDir, sprintf('jilublade_probe%d_nihe.mat', sensorId));
fallback = fullfile(caseDir, sprintf('jilublade_probe%d.mat', sensorId));

if exist(preferred, 'file') == 2
    probeFile = preferred;
elseif exist(fallback, 'file') == 2
    probeFile = fallback;
else
    probeFile = '';
end
end

function phaseRef = learn_low_speed_phase_reference_local(C, sensorIds, bladeCount)
phaseRef = repmat(struct('sensorId', NaN, 'alpha', NaN(1, bladeCount), ...
    'phaseDeg', NaN(1, bladeCount), 'usableRevCount', 0), numel(sensorIds), 1);

for is = 1:numel(sensorIds)
    P = C.probe(is);
    phaseRef(is).sensorId = sensorIds(is);
    if isempty(P.tCenter)
        continue;
    end

    slotAlpha = collect_slot_phases_local(C.opr.tCenter, P.tCenter, bladeCount);
    phaseRef(is).usableRevCount = size(slotAlpha, 1);
    phaseRef(is).alpha = median(slotAlpha, 1, 'omitnan');
    phaseRef(is).phaseDeg = 360 * phaseRef(is).alpha;
end
end

function Dcase = build_displacement_case_local(C, phaseRef, sensorIds, bladeCount, rTipMm)
Dcase = repmat(struct('sensorId', NaN, 'slot', []), numel(sensorIds), 1);

for is = 1:numel(sensorIds)
    P = C.probe(is);
    Dcase(is).sensorId = sensorIds(is);
    Dcase(is).slot = repmat(struct('bladeSlot', NaN, 'time', [], 'xMm', [], ...
        'phaseError', []), 1, bladeCount);
    for ib = 1:bladeCount
        Dcase(is).slot(ib).bladeSlot = ib;
    end
    if isempty(P.tCenter)
        continue;
    end

    slotData = collect_slot_phase_times_local(C.opr.tCenter, P.tCenter, bladeCount);
    alphaRef = phaseRef(is).alpha;

    for ib = 1:bladeCount
        alpha = slotData(ib).alpha;
        t = slotData(ib).time;
        phaseError = wrap_to_half_turn_local(alpha - alphaRef(ib));
        Dcase(is).slot(ib).time = t;
        Dcase(is).slot(ib).phaseError = phaseError;
        Dcase(is).slot(ib).xMm = rTipMm * 2 * pi * phaseError;
    end
end
end

function [Dphysical, numbering] = load_foundation_physical_displacement_local( ...
    foundationDir, sensorIds, bladeCount)
if exist(foundationDir, 'dir') ~= 7
    error('Foundation Step02 folder not found: %s', foundationDir);
end

Dphysical = repmat(struct('sensorId', NaN, 'slot', []), numel(sensorIds), 1);
sourceRows = repmat(struct('sensorId', NaN, 'validCount', 0, ...
    'sourceFile', ''), numel(sensorIds), 1);

for is = 1:numel(sensorIds)
    sid = sensorIds(is);
    sourceFile = fullfile(foundationDir, ...
        sprintf('jilublade_probe%d_vib_final.mat', sid));
    if exist(sourceFile, 'file') ~= 2
        error('Foundation physical blade displacement file not found: %s', sourceFile);
    end
    F = load(sourceFile, 'jilublade', 'metadata');
    rows = F.jilublade;
    if size(rows, 2) < 12
        error('Foundation vib_final file has fewer than 12 columns: %s', sourceFile);
    end
    valid = rows(:, 12) == 1 & isfinite(rows(:, 1)) & isfinite(rows(:, 2)) & ...
        isfinite(rows(:, 3)) & isfinite(rows(:, 4)) & isfinite(rows(:, 6)) & ...
        rows(:, 4) >= 1 & rows(:, 4) <= bladeCount;
    rows = rows(valid, :);

    Dphysical(is).sensorId = sid;
    Dphysical(is).slot = repmat(struct('bladeSlot', NaN, ...
        'physicalBladeId', NaN, 'time', [], 'xMm', [], 'phaseError', [], ...
        'pulseStart', [], 'pulseEnd', [], 'rpm', [], ...
        'foundationArrivalTime', []), 1, bladeCount);

    for bladeId = 1:bladeCount
        use = rows(:, 4) == bladeId;
        bladeRows = sortrows(rows(use, :), 3);
        Dphysical(is).slot(bladeId).bladeSlot = bladeId;
        Dphysical(is).slot(bladeId).physicalBladeId = bladeId;
        Dphysical(is).slot(bladeId).time = bladeRows(:, 3);
        Dphysical(is).slot(bladeId).xMm = bladeRows(:, 6);
        Dphysical(is).slot(bladeId).phaseError = bladeRows(:, 8) / 360;
        Dphysical(is).slot(bladeId).pulseStart = bladeRows(:, 1);
        Dphysical(is).slot(bladeId).pulseEnd = bladeRows(:, 2);
        Dphysical(is).slot(bladeId).rpm = bladeRows(:, 11);
        Dphysical(is).slot(bladeId).foundationArrivalTime = bladeRows(:, 3);
    end

    sourceRows(is).sensorId = sid;
    sourceRows(is).validCount = size(rows, 1);
    sourceRows(is).sourceFile = sourceFile;
    fprintf('Foundation physical displacement CH%d: loaded %d valid events.\n', ...
        sid, size(rows, 1));
end

numbering = struct();
numbering.scheme = 'foundation_physical_blade_id';
numbering.sourceDir = foundationDir;
numbering.oprFile = fullfile(foundationDir, 'jiluOPR.mat');
numbering.labelColumn = 'jilublade(:,4)';
numbering.displacementColumn = 'jilublade(:,6)';
numbering.pulseBoundsColumns = 'jilublade(:,1:2)';
numbering.physicalSensorIds = sensorIds;
numbering.sourceSummary = struct2table(sourceRows);
numbering.note = ['highDisp.slot(k) is physical blade k and is loaded directly ' ...
    'from Foundation Step03 vib_final products.'];
end

function slotAlpha = collect_slot_phases_local(oprTime, probeTime, bladeCount)
slotData = collect_slot_phase_times_local(oprTime, probeTime, bladeCount);
minCount = min(arrayfun(@(s) numel(s.alpha), slotData));
slotAlpha = NaN(minCount, bladeCount);
for ib = 1:bladeCount
    slotAlpha(:, ib) = slotData(ib).alpha(1:minCount);
end
end

function slotData = collect_slot_phase_times_local(oprTime, probeTime, bladeCount)
slotData = repmat(struct('time', [], 'alpha', []), 1, bladeCount);
probeTime = probeTime(:);

for iRev = 1:(numel(oprTime) - 1)
    t0 = oprTime(iRev);
    t1 = oprTime(iRev + 1);
    inRev = probeTime > t0 & probeTime < t1;
    tRev = sort(probeTime(inRev));

    if numel(tRev) < bladeCount
        continue;
    end

    % Keep the six most central events if an interval has extra edge points.
    alphaRev = (tRev - t0) ./ (t1 - t0);
    [~, order] = sort(abs(alphaRev - 0.5), 'ascend');
    keep = sort(order(1:bladeCount));
    tRev = tRev(keep);
    alphaRev = alphaRev(keep);

    for ib = 1:bladeCount
        slotData(ib).time(end + 1, 1) = tRev(ib);
        slotData(ib).alpha(end + 1, 1) = alphaRev(ib);
    end
end
end

function y = wrap_to_half_turn_local(x)
y = mod(x + 0.5, 1.0) - 0.5;
end

function print_phase_reference_local(phaseRef, sensorIds, bladeCount)
fprintf('Low-speed reference phase, degrees inside one OPR period:\n');
header = sprintf('Probe  usableRev');
for ib = 1:bladeCount
    header = sprintf('%s   B%d_deg', header, ib);
end
fprintf('%s\n', header);
for is = 1:numel(sensorIds)
    row = sprintf('%5d  %9d', sensorIds(is), phaseRef(is).usableRevCount);
    for ib = 1:bladeCount
        row = sprintf('%s  %7.2f', row, phaseRef(is).phaseDeg(ib));
    end
    fprintf('%s\n', row);
end
end

function print_displacement_summary_local(name, Dcase, sensorIds, bladeCount)
fprintf('\n%s displacement std, mm:\n', name);
header = sprintf('Probe');
for ib = 1:bladeCount
    header = sprintf('%s      B%d', header, ib);
end
fprintf('%s\n', header);

for is = 1:numel(sensorIds)
    row = sprintf('%5d', sensorIds(is));
    for ib = 1:bladeCount
        x = Dcase(is).slot(ib).xMm;
        row = sprintf('%s  %7.4f', row, std(x, 'omitnan'));
    end
    fprintf('%s\n', row);
end
end

function plot_phase_reference_local(phaseRef, sensorIds, bladeCount)
figure('Name', 'Step02 20241106 low-speed reference phase', 'Color', 'w');
phaseMat = NaN(numel(sensorIds), bladeCount);
for is = 1:numel(sensorIds)
    phaseMat(is, :) = phaseRef(is).phaseDeg;
end
plot(1:bladeCount, phaseMat.', 'o-', 'LineWidth', 1.0);
grid on; box on;
xlabel('Blade slot relative to 20241106 OPR');
ylabel('Reference phase in one OPR period (deg)');
legend(compose('Probe %d', sensorIds), 'Location', 'best');
title('Low-speed 900 rpm timing reference');
end

function plot_speed_and_target_blade_local(C, Dcase, sensorIds, targetBladeSlot)
figure('Name', 'Step02 20241106 high-speed target blade displacement', 'Color', 'w');
tiledlayout(2, 1, 'TileSpacing', 'compact', 'Padding', 'compact');

nexttile;
plot(C.speedTime, C.rpm, 'k-', 'LineWidth', 1.0);
grid on; box on;
xlabel('Time (s)');
ylabel('Speed (rpm)');
title('High-speed OPR speed');

nexttile; hold on;
for is = 1:numel(sensorIds)
    S = Dcase(is).slot(targetBladeSlot);
    plot(S.time, S.xMm, '.', 'MarkerSize', 4, ...
        'DisplayName', sprintf('Probe %d', sensorIds(is)));
end
grid on; box on;
xlabel('Time (s)');
ylabel('Relative displacement (mm)');
title(sprintf('High-speed displacement, blade slot %d', targetBladeSlot));
legend('Location', 'best');
end

function plot_sensor_slot_overview_local(Dcase, sensorIds, bladeCount)
figure('Name', 'Step02 20241106 high-speed all blade slots', 'Color', 'w');
tiledlayout(numel(sensorIds), 1, 'TileSpacing', 'compact', 'Padding', 'compact');

for is = 1:numel(sensorIds)
    nexttile; hold on;
    for ib = 1:bladeCount
        S = Dcase(is).slot(ib);
        plot(S.time, S.xMm, '.', 'MarkerSize', 2, ...
            'DisplayName', sprintf('B%d', ib));
    end
    grid on; box on;
    ylabel(sprintf('P%d mm', sensorIds(is)));
    if is == 1
        title('High-speed displacement by probe and blade slot');
    end
    if is == numel(sensorIds)
        xlabel('Time (s)');
    end
end
legend('Location', 'bestoutside');
end

function plot_low_speed_self_check_local(Dcase, sensorIds, targetBladeSlot)
figure('Name', 'Step02 20241106 low-speed self-check', 'Color', 'w');
hold on;
for is = 1:numel(sensorIds)
    S = Dcase(is).slot(targetBladeSlot);
    plot(S.time, S.xMm, '.', 'MarkerSize', 4, ...
        'DisplayName', sprintf('Probe %d', sensorIds(is)));
end
grid on; box on;
xlabel('Time (s)');
ylabel('Relative displacement (mm)');
title(sprintf('Low-speed self-check, blade slot %d should stay near 0', targetBladeSlot));
legend('Location', 'best');
end
