function [scenarioList, snrList] = make_multicase_scenarios_vibration_compare()
%make_multicase_scenarios_vibration_compare
% Fixed fs/NumRevs experiment set for comparing vibration working conditions only.

snrList = [20, 10, 5, 0];
numRepeat = 5;
baseSeed = 20260503;

baseScenarios = struct( ...
    'name', { ...
        "single_sync_500", ...
        "single_async_1330", ...
        "dual_sync_async_500_1300", ...
        "dual_sync_async_500_1330"}, ...
    'A_true', { ...
        [0.25], ...
        [0.15], ...
        [0.25, 0.15], ...
        [0.25, 0.15]}, ...
    'f_true', { ...
        [500], ...
        [1330], ...
        [500, 1300], ...
        [500, 1330]}, ...
    'phi_true', { ...
        [pi/4], ...
        [-pi/3], ...
        [pi/4, -pi/3], ...
        [pi/4, -pi/3]});

scenarioList = repmat(struct( ...
    'name', "", ...
    'A_true', [], ...
    'f_true', [], ...
    'phi_true', [], ...
    'repeat_id', NaN, ...
    'seed', NaN), numel(baseScenarios) * numRepeat, 1);

idx = 0;
for is = 1:numel(baseScenarios)
    for ir = 1:numRepeat
        idx = idx + 1;
        scenarioList(idx).name = string(baseScenarios(is).name);
        scenarioList(idx).A_true = baseScenarios(is).A_true;
        scenarioList(idx).f_true = baseScenarios(is).f_true;
        scenarioList(idx).phi_true = baseScenarios(is).phi_true;
        scenarioList(idx).repeat_id = ir;
        scenarioList(idx).seed = baseSeed + 100 * is + ir;
    end
end
end
