clc; close all;

%CALIBRATE_STEP05_JOINTSTATICETA_FROMPREVIEW_20241106
% Diagnostic only: estimate a fixed residual eta_s from saved NoEta Step05
% preview bundles, then compare it with free window eta and Step04 xc.

this_dir = fileparts(mfilename('fullpath'));
addpath(fileparts(this_dir));

noeta_file = fullfile(this_dir, 'output', ...
    'step05_eta_controlled_compare', 'NoEta', '3000_3150', ...
    'Result_Step05_EtaCompareNoEta_B4_S257_20241106.mat');

free_eta_file = fullfile(this_dir, 'output', ...
    'step05_eta_controlled_compare', 'WithEta', '3000_3150', ...
    'Result_Step05_EtaCompareWithEta_B4_S257_20241106.mat');

template_file = fullfile(this_dir, 'output', ...
    'step04_low_speed_template', ...
    'Template_OPRCenterStd_LowSpeed_AllBlades_S2357_20241106.mat');

out_dir = fullfile(this_dir, 'output', ...
    'step05_joint_static_eta_preview');

Summary = Calibrate_Step05_JointStaticEta_FromPreview(this_dir, ...
    'NoEtaResultFile', noeta_file, ...
    'FreeEtaResultFile', free_eta_file, ...
    'Step04TemplateFile', template_file, ...
    'OutputDir', out_dir, ...
    'GradientMinRatio', 0.08, ...
    'QAbsLimitMm', 1.50, ...
    'HuberIterations', 4, ...
    'MinWindows', 3, ...
    'MinPointsPerSensorWindow', 60, ...
    'Verbose', true);

