clc; close all;

%CALIBRATE_STEP05_JOINTSTATICETA_FROMPREVIEW_20251222
% Diagnostic prerequisite for the formal fixed-eta Step05 route.
% Estimate eta_s from saved NoEta dynamic residual previews. 20251222 B1
% NoEta windows are EO-mixed, so each window uses its own base EO during the
% linearized calibration instead of forcing the final joint EO.

this_dir = fileparts(mfilename('fullpath'));
addpath(fileparts(this_dir));

noeta_file_env = strtrim(getenv('STEP05_NOETA_RESULT_FILE'));
if ~isempty(noeta_file_env)
    noeta_file = noeta_file_env;
else
    noeta_file = resolve_current_noeta_result_file_local(this_dir);
end

template_file = fullfile(this_dir, 'output', ...
    'step04_low_speed_template', ...
    'Template_OPRCenterStd_LowSpeed_AllBlades_S123_20251222.mat');

out_dir = fullfile(this_dir, 'output', ...
    'step05_joint_static_eta_preview');

Summary = Calibrate_Step05_JointStaticEta_FromPreview(this_dir, ...
    'NoEtaResultFile', noeta_file, ...
    'FreeEtaResultFile', '', ...
    'Step04TemplateFile', template_file, ...
    'OutputDir', out_dir, ...
    'CalibrationEO', 'window_base', ...
    'ConsensusPlanPolicy', 'primary_all_ok', ...
    'ConsensusIQRWarnMm', 0.15, ...
    'GradientMinRatio', 0.08, ...
    'QAbsLimitMm', 1.50, ...
    'HuberIterations', 4, ...
    'MinWindows', 3, ...
    'MinPointsPerSensorWindow', 60, ...
    'Verbose', true);


function noeta_file = resolve_current_noeta_result_file_local(this_dir)
case_name = '1000_2500_3500';
dataset = '20251222';
target_blade = 1;
sensor_tag = 'S123';

candidates = {
    fullfile(this_dir, 'output', 'step05_single_sync_direct_template', ...
    case_name, sprintf('Result_Step05_NoEtaGradDispVP_B%d_%s_%s.mat', ...
    target_blade, sensor_tag, dataset))
    fullfile(this_dir, 'output', 'step05_single_sync_direct_template_gdisp18', ...
    case_name, sprintf('Result_Step05_NoEtaGradDispVP_B%d_%s_%s.mat', ...
    target_blade, sensor_tag, dataset))
    fullfile(this_dir, 'output', 'step05_single_sync_direct_template_gdisp_smoke', ...
    case_name, sprintf('Result_Step05_NoEtaGradDispVP_B%d_%s_%s.mat', ...
    target_blade, sensor_tag, dataset))
    };

for i = 1:numel(candidates)
    if isfile(candidates{i})
        noeta_file = candidates{i};
        return;
    end
end

error(['No current NoEtaGradDispVP Step05 result found. Run the official ' ...
    'NoEta Step05 first, or set STEP05_NOETA_RESULT_FILE. Tried: %s'], ...
    strjoin(candidates, newline));
end
