%% Compare_UnifiedTheory_20251222
% Paired comparison of the archived formal route and the unified route.
% The comparison is deliberately based on the final complete-voltage fits.

clear; clc;

thisDir = fileparts(mfilename('fullpath'));
pkgDir = fileparts(fileparts(thisDir));
resultDir = fullfile(pkgDir, 'results', 'gap_aware');

cases = struct( ...
    'region', {'R01','R07','R04'}, ...
    'oldFile', { ...
        'Main_GapAware_VPTopK_FullWave_20251222_B1_S123_r01_gapaware.mat', ...
        'Main_GapAware_VPTopK_FullWave_20251222_B1_S123_r07_gapaware.mat', ...
        'Main_GapAware_VPTopK_FullWave_20251222_B5_S123_r04_gapaware.mat'}, ...
    'newFile', { ...
        'Main_GapAware_VPTopK_FullWave_20251222_B1_S123_unified_structured_voltage_r01_20260811.mat', ...
        'Main_GapAware_VPTopK_FullWave_20251222_B1_S123_unified_structured_voltage_r07_20260811.mat', ...
        'Main_GapAware_VPTopK_FullWave_20251222_B5_S123_unified_structured_voltage_r04_20260811.mat'});

detail = table();
summary = table();
for i = 1:numel(cases)
    old = load(fullfile(resultDir, cases(i).oldFile), 'Result');
    new = load(fullfile(resultDir, cases(i).newFile), 'Result');
    a = old.Result.Trend;
    b = new.Result.Trend;
    assert(height(a) == height(b), 'Window count mismatch for %s.', cases(i).region);

    n = height(a);
    region = repmat(string(cases(i).region), n, 1);
    D = table(region, a.window_id, a.gap_EO, b.gap_EO, ...
        a.gap_frequency_hz, b.gap_frequency_hz, ...
        a.gap_amplitude_mm, b.gap_amplitude_mm, ...
        a.gap_dx_mm, b.gap_dx_mm, a.gap_rmse_mV, b.gap_rmse_mV, ...
        'VariableNames', {'region','window_id','old_EO','new_EO', ...
        'old_frequency_hz','new_frequency_hz','old_amplitude_mm', ...
        'new_amplitude_mm','old_dx_mm','new_dx_mm','old_plain_rmse_mV', ...
        'new_plain_rmse_mV'});
    D.delta_frequency_hz = D.new_frequency_hz - D.old_frequency_hz;
    D.delta_amplitude_mm = D.new_amplitude_mm - D.old_amplitude_mm;
    D.delta_dx_mm = D.new_dx_mm - D.old_dx_mm;
    D.delta_plain_rmse_mV = D.new_plain_rmse_mV - D.old_plain_rmse_mV;
    detail = [detail; D]; %#ok<AGROW>

    S = table(string(cases(i).region), n, sum(D.old_EO ~= D.new_EO), ...
        mean(D.old_plain_rmse_mV), mean(D.new_plain_rmse_mV), ...
        mean(D.delta_plain_rmse_mV), max(D.delta_plain_rmse_mV), ...
        mean(D.old_amplitude_mm), mean(D.new_amplitude_mm), ...
        mean(D.delta_amplitude_mm), mean(abs(D.delta_amplitude_mm)), ...
        std(D.old_amplitude_mm), std(D.new_amplitude_mm), ...
        'VariableNames', {'region','window_count','EO_changed_count', ...
        'old_mean_plain_rmse_mV','new_mean_plain_rmse_mV', ...
        'mean_delta_plain_rmse_mV','max_delta_plain_rmse_mV', ...
        'old_mean_amplitude_mm','new_mean_amplitude_mm', ...
        'mean_delta_amplitude_mm','mean_abs_delta_amplitude_mm', ...
        'old_amplitude_std_mm','new_amplitude_std_mm'});
    summary = [summary; S]; %#ok<AGROW>
end

writetable(detail, fullfile(thisDir, 'UnifiedTheory_WindowComparison_20251222.csv'));
writetable(summary, fullfile(thisDir, 'UnifiedTheory_RegionSummary_20251222.csv'));
disp(summary);

