function C = R5_Summarize_Main10_Comparison(baselineSummary,r5Summary,outputFile)
% Compare the unchanged Main10 result with the R4 front-end sidecar input.
if nargin<1 || isempty(baselineSummary), error('R5:MissingBaseline','baseline summary CSV is required.'); end
if nargin<2 || isempty(r5Summary), error('R5:MissingR5','R5 summary CSV is required.'); end
if nargin<3 || isempty(outputFile), outputFile=fullfile(fileparts(mfilename('fullpath')),'results','R5_Main10_Comparison.csv'); end
A=readtable(baselineSummary); B=readtable(r5Summary);
assert(height(A)==1 && height(B)==1,'R5:SummarySchema','Expected one gap_only summary row per run.');
C=table(string(A.method),A.dominant_EO,B.dominant_EO,A.mean_frequency_hz, ...
    B.mean_frequency_hz,B.mean_frequency_hz-A.mean_frequency_hz, ...
    A.std_frequency_hz,B.std_frequency_hz,A.mean_rmse_mV,B.mean_rmse_mV, ...
    B.mean_rmse_mV-A.mean_rmse_mV,A.mean_amplitude_mm,B.mean_amplitude_mm, ...
    'VariableNames',{'method','baseline_EO','r5_EO','baseline_mean_frequency_hz', ...
    'r5_mean_frequency_hz','frequency_difference_hz','baseline_frequency_std_hz', ...
    'r5_frequency_std_hz','baseline_mean_rmse_mV','r5_mean_rmse_mV', ...
    'rmse_difference_mV','baseline_mean_amplitude_mm','r5_mean_amplitude_mm'});
if ~exist(fileparts(outputFile),'dir'), mkdir(fileparts(outputFile)); end
writetable(C,outputFile);
end
