%% Clean strict-V3 ranking without modifying raw comparison outputs.
clear; clc;
thisDir=fileparts(mfilename('fullpath')); outDir=fullfile(thisDir,'results');
inFile=fullfile(outDir,'StrictV3_MethodComparison_Summary_20251222.csv');
S=readtable(inFile,'TextType','string');
% Keep only methods declared by the current comparison script.
valid=["R1_pooled_increment","R2_oracle_basegap_conditioned", ...
 "R3raw_plus_R2","R3raw_plus_R4","R3gain_plus_R4","R3nearest_surface", ...
 "R3_top2_surface_ensemble","R3_top3_surface_ensemble","R3_convex_surface_ensemble", ...
 "R3_shifted_nearest_surface","R3_peak_aligned_nearest_surface", ...
 "R3_affine_x_nearest_surface","R3_weighted_shift_nearest_g1", ...
 "R3_weighted_shift_nearest_g2","R3_affine_gain_offset_shifted_surface", ...
 "R3_centered_shift_nearest_surface","R3_shape_normalized_shift_nearest_surface", ...
 "R3_regularized_affine_shift_nearest_surface","R3_peak_feature_shift_nearest_surface", ...
 "R3_continuous_affine_shifted_surface"];
S=S(ismember(S.method,valid),:);
outSummary=fullfile(outDir,'StrictV3_MethodComparison_Summary_20251222_clean.csv');
writetable(S,outSummary);
% Pareto candidates: direct P90 target error versus P90 baseline ratio.
deploy=S(~contains(S.method,"oracle") & ~startsWith(S.method,"R1_"),:);
keep=true(height(deploy),1);
for i=1:height(deploy)
    dominated=deploy.P90TransferRMSEmV<=deploy.P90TransferRMSEmV(i) & ...
        deploy.P90TransferToBaselineRatio<=deploy.P90TransferToBaselineRatio(i) & ...
        (deploy.P90TransferRMSEmV<deploy.P90TransferRMSEmV(i) | ...
         deploy.P90TransferToBaselineRatio<deploy.P90TransferToBaselineRatio(i));
    keep(i)=~any(dominated);
end
P=deploy(keep,:);
writetable(P,fullfile(outDir,'StrictV3_ParetoCandidates_20251222.csv'));
fprintf('Clean methods: %d; deployable Pareto candidates: %d\n',height(S),height(P));
disp(P(:,{'method','P50TransferRMSEmV','P90TransferRMSEmV','P90TransferToBaselineRatio'}));
