function Study = Config_ParameterStudy_20241106()
%CONFIG_PARAMETERSTUDY_20241106 One-factor parameter-study definitions.
% Formal eta=0 and plain-RMSE settings are intentionally not study factors.

Study = struct();
Study.version = 'PARAMETER_STUDY_V1_20260715';
packageRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
Study.outputRoot = fullfile(packageRoot, 'results', 'study');
Study.formalPrograms = [7 8 9];

Cases = repmat(empty_case_local(), 0, 1);
Cases(end+1) = make_case_local('baseline', 'baseline', ...
    'Frozen formal configuration', struct(), struct());

Cases(end+1) = make_case_local('vp_topk_2', 'vp_top_k', ...
    'VP Top-K = 2', nested_override_local('frequency', 'vpTopK', 2), struct());
Cases(end+1) = make_case_local('vp_topk_3', 'vp_top_k', ...
    'VP Top-K = 3', nested_override_local('frequency', 'vpTopK', 3), struct());
Cases(end+1) = make_case_local('vp_topk_5', 'vp_top_k', ...
    'VP Top-K = 5', nested_override_local('frequency', 'vpTopK', 5), struct());

Cases(end+1) = make_case_local('df_pm0p5hz', 'frequency_refine', ...
    'Candidate frequency refinement +/-0.5 Hz', ...
    nested_override_local('frequency', 'refineHalfWidthHz', 0.5), struct());
Cases(end+1) = make_case_local('df_pm2hz', 'frequency_refine', ...
    'Candidate frequency refinement +/-2 Hz', ...
    nested_override_local('frequency', 'refineHalfWidthHz', 2.0), struct());
Cases(end+1) = make_case_local('df_pm5hz', 'frequency_refine', ...
    'Candidate frequency refinement +/-5 Hz', ...
    nested_override_local('frequency', 'refineHalfWidthHz', 5.0), struct());

Cases(end+1) = make_case_local('gap_limit_0p05mm', 'gap_limit', ...
    'Gap increment bound +/-0.05 mm', ...
    nested_override_local('model', 'deltaGapLimitMm', 0.05), struct());
Cases(end+1) = make_case_local('gap_limit_0p10mm', 'gap_limit', ...
    'Gap increment bound +/-0.10 mm', ...
    nested_override_local('model', 'deltaGapLimitMm', 0.10), struct());
Cases(end+1) = make_case_local('gap_limit_0p25mm', 'gap_limit', ...
    'Gap increment bound +/-0.25 mm', ...
    nested_override_local('model', 'deltaGapLimitMm', 0.25), struct());

Cases(end+1) = make_case_local('window_3lap', 'window_size', ...
    'Three-pass sliding window', ...
    nested_override_local('window', 'windowBladePasses', 3), struct());
Cases(end+1) = make_case_local('window_5lap', 'window_size', ...
    'Five-pass sliding window', ...
    nested_override_local('window', 'windowBladePasses', 5), struct());

Cases(end+1) = make_case_local('vp_weight_power_1', 'vp_weight_power', ...
    'VP gradient weight power = 1', struct(), ...
    struct('STEP07J_VP_GRADIENT_WEIGHT_POWER', '1'));
Cases(end+1) = make_case_local('vp_weight_power_2', 'vp_weight_power', ...
    'VP gradient weight power = 2', struct(), ...
    struct('STEP07J_VP_GRADIENT_WEIGHT_POWER', '2'));
Cases(end+1) = make_case_local('vp_weight_power_3', 'vp_weight_power', ...
    'VP gradient weight power = 3', struct(), ...
    struct('STEP07J_VP_GRADIENT_WEIGHT_POWER', '3'));

Study.Cases = Cases;
Study.groups = unique(string({Cases.group}), 'stable');
end


function C = empty_case_local()
C = struct('name', '', 'group', '', 'description', '', ...
    'override', struct(), 'environment', struct());
end


function C = make_case_local(name, group, description, override, environment)
C = empty_case_local();
C.name = name;
C.group = group;
C.description = description;
C.override = override;
C.environment = environment;
end


function value = nested_override_local(section, name, setting)
value = struct();
value.(section) = struct(name, setting);
end
