function cfg = Setup_Paths_20251222()
%SETUP_PATHS_20251222 Add only paths owned by this V1 package.
rootDir = fileparts(mfilename('fullpath'));
addpath(rootDir, fullfile(rootDir, 'functions', 'preparation'), ...
    fullfile(rootDir, 'functions', 'foundation'), ...
    fullfile(rootDir, 'functions', 'calibration'), ...
    fullfile(rootDir, 'functions', 'gap_aware'), ...
    fullfile(rootDir, 'functions', 'utilities'));
cfg = Config_20251222();
ownedDirs = {cfg.paths.prepared, cfg.paths.preparedLegacy, ...
    cfg.paths.calibrationWork, cfg.paths.foundationResults, ...
    cfg.paths.gapResults, cfg.paths.comparison, ...
    cfg.paths.strainValidation, cfg.paths.figures};
for i = 1:numel(ownedDirs)
    if exist(ownedDirs{i}, 'dir') ~= 7
        mkdir(ownedDirs{i});
    end
end
end
