%% Summarize the one-way production pipeline against the prior P3 result.
clear; clc;
thisDir=fileparts(mfilename('fullpath'));
caseDir=fileparts(fileparts(thisDir));
outDir=fullfile(thisDir,'outputs');
newFile=fullfile(caseDir,'results','gap_aware', ...
    'Step07J_NestedStaticWarp_VPFullWave_20250527_B1_S136_oneway_joint_prod_20260831.mat');
oldFile=fullfile(caseDir,'analysis','transfer_identifiability_20260830','outputs', ...
    'NestedTransferHighSpeedSummary_20250527.csv');
S=load(newFile,'Result'); W=S.Result.WindowResult;
freq=arrayfun(@(w)w.modelFits.gap_only.freqHz,W);
amp=arrayfun(@(w)w.modelFits.gap_only.amplitudeMm,W);
rmse=arrayfun(@(w)w.modelFits.gap_only.plainRmseMv,W);
eo=arrayfun(@(w)w.modelFits.gap_only.EO,W);
D=nan(numel(W),3);
for i=1:numel(W), D(i,:)=W(i).modelFits.gap_only.deltaGapMm(:).'; end
New=table("oneway_joint_production",mode(eo),sum(eo==14),mean(freq),std(freq), ...
    mean(amp),std(amp),mean(rmse),median(rmse),mean(D,'all'), ...
    mean(D(:,1)),mean(D(:,2)),mean(D(:,3)), ...
    'VariableNames',{'model','dominantEO','eo14WindowCount','meanFrequencyHz', ...
    'stdFrequencyHz','meanAmplitudeMm','stdAmplitudeMm','meanWaveformRmseMv', ...
    'medianWaveformRmseMv','meanDeltaGapMm','meanDeltaGapCH1Mm', ...
    'meanDeltaGapCH3Mm','meanDeltaGapCH6Mm'});
OldAll=readtable(oldFile,'TextType','string');
O=OldAll(OldAll.model=="P3_full_transfer",:);
Old=table("prior_P3_full_transfer",O.dominantEO,O.eo14WindowCount,O.meanFrequencyHz, ...
    O.stdFrequencyHz,O.meanAmplitudeMm,O.stdAmplitudeMm,O.meanWaveformRmseMv, ...
    O.medianWaveformRmseMv,O.meanDeltaGapMm,O.meanDeltaGapCH1Mm, ...
    O.meanDeltaGapCH3Mm,O.meanDeltaGapCH6Mm,'VariableNames',New.Properties.VariableNames);
Comparison=[Old;New];
writetable(Comparison,fullfile(outDir,'ProductionHighSpeedComparison_20250527.csv'));
Delta=table(New.meanFrequencyHz-Old.meanFrequencyHz,New.meanAmplitudeMm-Old.meanAmplitudeMm, ...
    New.meanWaveformRmseMv-Old.meanWaveformRmseMv,New.meanDeltaGapMm-Old.meanDeltaGapMm, ...
    New.meanDeltaGapCH3Mm-Old.meanDeltaGapCH3Mm, ...
    'VariableNames',{'frequencyChangeHz','amplitudeChangeMm','rmseChangeMv', ...
    'meanDeltaGapChangeMm','CH3DeltaGapChangeMm'});
writetable(Delta,fullfile(outDir,'ProductionHighSpeedDifference_20250527.csv'));
disp(Comparison); disp(Delta);
