function Files=Plot_R3_Fig3_SixPanel_Ready()
root=fileparts(mfilename('fullpath'));S=load(fullfile(root,'output','18_paper_data_sync','r3_paper_result.mat'),'Result');R=S.Result;P=R.P;g=sort(P.gMainMm);A=P.amplitudeMainMm;fig=figure('Color','w','Units','centimeters','Position',[1 1 17 17.2]);t=tiledlayout(fig,3,2,'TileSpacing','compact','Padding','compact');
ax=nexttile(t);hold(ax,'on');plot(ax,P.gAllMm,zeros(size(P.gAllMm)),'-','Color',[.75 .75 .75]);scatter(ax,P.gCalMm,zeros(size(P.gCalMm)),34,[.25 .25 .25],'filled');scatter(ax,P.gOperatingMm,zeros(size(P.gOperatingMm)),38,[0 .45 .62],'filled');scatter(ax,P.gReferenceMm,0,64,[.78 .29 .20],'o','LineWidth',1.2);xlim(ax,[.15 1.55]);ylim(ax,[-.3 .3]);set(ax,'YTick',[],'XTick',.2:.1:1.5);xlabel(ax,'Clearance, g (mm)');title(ax,'Frozen calibration and held-out test design');text(ax,.3,.2,'calibration','FontSize',8);text(ax,1,-.18,'held-out','Color',[0 .35 .5],'FontSize',8);style(ax);tag(ax,'a');
ax=nexttile(t);mainDir=fileparts(root);addpath(fullfile(root,'local_func'),'-begin');addpath(fullfile(mainDir,'local_func'),'-begin');C=load(fullfile(root,'output','02_reference_calibration','r3_reference_calibration_C0.mat'),'Result');C0=C.Result.C0;sigmaV=C.Result.sigmaV;R3=r3_build_context(mainDir,P);[~,map,truth]=r3_generate_high_case(R3,.7,.20,P.phaseValuesRad(1),sigmaV,P.mainHighSeeds(1));F=r3_run_three_methods_global_final(R3,C0,map,.7);n=min([numel(map.t_v),numel(map.V_a),numel(F.fixed.VFit),numel(F.adaptive.VFit),2500]);plot(ax,map.t_v(1:n),map.V_a(1:n),'.','Color',[.35 .35 .35],'MarkerSize',2,'DisplayName','Measured');hold(ax,'on');plot(ax,map.t_v(1:n),F.fixed.VFit(1:n),'-','Color',[.2 .2 .2],'LineWidth',.8,'DisplayName','Fixed fit');plot(ax,map.t_v(1:n),F.adaptive.VFit(1:n),'-','Color',[0 .45 .62],'LineWidth',.9,'DisplayName','Adaptive fit');xlabel(ax,'Time (s)');ylabel(ax,'Sensor voltage (V)');title(ax,'Representative record: g=0.7 mm, A=0.20 mm');legend(ax,'Location','best','Box','off','FontSize',7);text(ax,.02,.97,sprintf('truth EO=10\\nFixed EO=%d\\nAdaptive EO=%d',truth.eo_true,F.fixed.eo_id,F.adaptive.eo_id),'Units','normalized','VerticalAlignment','top','FontSize',7.2,'BackgroundColor','w');style(ax);tag(ax,'b');
drawmap(nexttile(t),R.Summary,"fixed",g,A,'P_vib','Fixed reference');tag(gca,'c');drawmap(nexttile(t),R.Summary,"adaptive",g,A,'P_vib','Clearance adaptive');tag(gca,'d');drawmap(nexttile(t),R.Paired,"paired",g,A,'P_rescue','Paired adaptive rescue');tag(gca,'e');drawfail(nexttile(t),R.FailureByGap);tag(gca,'f');
colormap(fig,parula(256));title(t,'Synchronous-vibration recovery under matched and held-out clearance states','FontName','Times New Roman','FontSize',9,'FontWeight','normal');out=fullfile(root,'output','figures_final');if ~exist(out,'dir'),mkdir(out);end;base=fullfile(out,'Fig3_R3_six_panel_evidence_ready');exportgraphics(fig,[base '.png'],'Resolution',600);exportgraphics(fig,[base '.pdf'],'ContentType','vector');exportgraphics(fig,[base '.emf'],'ContentType','vector');Files=struct('png',[base '.png'],'pdf',[base '.pdf'],'emf',[base '.emf']);
end
function drawmap(ax,T,m,g,A,v,ttl),Z=NaN(numel(A),numel(g));for ia=1:numel(A),for ig=1:numel(g),if m=="paired",q=abs(T.g_truth_mm-g(ig))<1e-12&abs(T.A_true_mm-A(ia))<1e-12;else,q=T.method==m&abs(T.g_truth_mm-g(ig))<1e-12&abs(T.A_true_mm-A(ia))<1e-12;end;if any(q),Z(ia,ig)=T.(v)(find(q,1));end;end;end;imagesc(ax,g-.8,A,Z);set(ax,'YDir','normal','CLim',[0 1],'XTick',g-.8,'YTick',A);xlabel(ax,'Clearance mismatch, \Delta g (mm)');ylabel(ax,'Vibration amplitude, A (mm)');title(ax,ttl);style(ax);end
function drawfail(ax,T),cats=["EO","EO + amplitude","EO + phase","EO + amplitude + phase"];gg=sort(unique(T.g_truth_mm));M=zeros(numel(gg),numel(cats));for i=1:numel(gg),for j=1:numel(cats),q=T.g_truth_mm==gg(i)&T.failure_pattern==cats(j);if any(q),M(i,j)=T.fraction_of_failures(find(q,1));end;end;end;bar(ax,gg,M,'stacked');ylim(ax,[0 1]);xlabel(ax,'True clearance, g (mm)');ylabel(ax,'Fraction of Fixed failures');title(ax,'Fixed failure-mode composition');legend(ax,cats,'Location','southoutside','Orientation','horizontal','Box','off','FontSize',6.5);style(ax);end
function style(ax),set(ax,'FontName','Times New Roman','FontSize',8,'LineWidth',.75,'TickDir','in','Box','on','Layer','top','XGrid','off','YGrid','off');end
function tag(ax,s),text(ax,-.13,1.06,['(' s ')'],'Units','normalized','FontName','Times New Roman','FontSize',8.5);end
