function T = make_ortho_summary(R, truth)
%make_ortho_summary  Build a one-row method summary table.

[fTrue, order] = sort(truth.f(:).');
ATrue = truth.A(order);
T = table(R.method, R.g_used, abs(R.g_used - truth.g_high), ...
    R.f_id(1), R.f_id(2), R.A_id(1), R.A_id(2), ...
    mean(abs(R.f_id - fTrue)), mean(abs(R.A_id - ATrue)), ...
    R.rmse, R.eta_g, R.elapsed_s, ...
    'VariableNames', {'method','gap_used_mm','gap_error_mm', ...
    'f1_Hz','f2_Hz','A1_mm','A2_mm','mean_freq_error_Hz', ...
    'mean_amp_error_mm','rmse','eta_g','elapsed_s'});
end
