function save_fixed_trust_domain(thisDir, trustInfo, modelDef, cfgAna)
%save_fixed_trust_domain  Persist calibrated trust-domain information.

trustPath = get_trust_result_path(thisDir);
trustCsv = strrep(trustPath, '.mat', '_summary.csv');
trustMetricsCsv = strrep(trustPath, '.mat', '_metrics.csv');

summary = table( ...
    string(modelDef.model_label(1)), ...
    string(modelDef.response_model(1)), ...
    string(modelDef.basis_name(1)), ...
    trustInfo.domain(1), ...
    trustInfo.domain(2), ...
    trustInfo.selectedHalfWidth, ...
    trustInfo.fullDomain(1), ...
    trustInfo.fullDomain(2), ...
    trustInfo.effectiveDomain(1), ...
    trustInfo.effectiveDomain(2), ...
    string(trustInfo.selectionMode), ...
    'VariableNames', {'model_label','response_model','basis_name', ...
    'trust_x_min_mm','trust_x_max_mm','trust_half_width_mm', ...
    'full_x_min_mm','full_x_max_mm','effective_x_min_mm', ...
    'effective_x_max_mm','selection_mode'});

save(trustPath, 'trustInfo', 'modelDef', 'cfgAna', 'summary', '-v7.3');
writetable(summary, trustCsv);
if isfield(trustInfo, 'metrics')
    writetable(trustInfo.metrics, trustMetricsCsv);
end
end
