function add_inv_log_2_panel_labels(axList, labels)
%add_inv_log_2_panel_labels  Place panel labels at the upper-left corner.

labels = string(labels);
for iax = 1:numel(axList)
    text(axList(iax), -0.075, 1.035, labels(iax), ...
        'Units', 'normalized', ...
        'FontName', 'Times New Roman', ...
        'FontSize', 9, ...
        'FontWeight', 'normal', ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'bottom', ...
        'Clipping', 'off');
end
end
