function R=Probe_NoGap5001300Oracle()
root=fileparts(mfilename('fullpath'));mainDir=fileparts(root);addpath(mainDir,'-begin');addpath(fullfile(mainDir,'local_func'),'-begin');
ctx=load_inv_log_2_project_context(mainDir);tr=load_fixed_trust_domain(mainDir);lib=make_fixed_trust_template_library(ctx.gapList,ctx.xCell,ctx.yCell,NaN,ctx.cfgAna.xGridN,get_inv_log_2_model_def(),tr);
cfg=configure_structured_identification(make_inv_log_2_demo_case(ctx,.2).cfgCase,"experiment_current");cfg.RPM_low=min(cfg.RPM_high,300);cfg.NumRevs_low=20;cfg.NumRevs_high=4;cfg.structuredMinRevolutions=4;cfg.route30ForwardModel="low_increment";cfg.route30LowTemplateMethod="adaptive_sg";cfg.route30SupportAware=true;cfg.route30FrequencyStructureMode="dual_sync_sync";cfg.route30DualFrequencyRangeHz=[300 1500];cfg.route30LowTemplateOptions=struct('gridSpacingMm',.02,'minBinCount',5,'minCoverage',.90,'numFolds',5,'candidateWindowMm',[.10 .18 .34 .50 .82 1.22 1.62 2.02 2.42]);cfg.dualSyncGapCount=11;cfg.dualSyncKeepPerGap=80;cfg.dualSyncIteratedReplayCount=2100;cfg.dualSyncRefineCount=50;cfg.funnelAllPairsFirstJointStep=true;cfg.funnelSecondJointPairCount=24;cfg.funnelFullRefineCount=3;cfg.structuredComponentAmplitudeFloorMm=.05;
cfg.dualSyncSearchStrategy="funnel_v1";cfg.returnDualSyncDiagnostics=true;
low=simulate_low_speed_template(@(z)eval_gap_template(lib,.5,z),cfg,lib.domain,Inf,771001,'fixed_std');d=simulate_rotating_waveform_from_template(@(z)eval_gap_template(lib,.6,z),cfg.RPM_high,4,cfg.fs,cfg.R_tip,cfg.alpha_k,0,lib.domain,[.25 .15],[500 1300],[pi/4 -pi/6],'fixed_std');sigma=sqrt(var(d.V_clean,1))/10^(20/20);rng(772001,'twister');d.V_cap=d.V_clean+sigma*randn(size(d.V_clean));map=map_highspeed_to_space(d,cfg.alpha_k,cfg.R_tip,lib.domain,.02);
free=run_inv_log_2_structured_main(low,map,lib,cfg,"dual_sync_sync");cfg.dualSyncCandidateEOPairs=[10 26];oracle=run_inv_log_2_structured_main(low,map,lib,cfg,"dual_sync_sync");
q=all(free.diagnostic_pair_eo==[10 26],2);[~,ord]=sort(free.diagnostic_pair_gn1_score,'ascend');rank=zeros(size(ord));rank(ord)=1:numel(ord);
R=struct('free_eo',free.eo_id,'free_f',free.f_id,'free_rmse',free.rmse,'oracle_eo',oracle.eo_id,'oracle_f',oracle.f_id,'oracle_rmse',oracle.rmse,'free_A',free.A_id,'oracle_A',oracle.A_id,'free_g',free.g_used,'oracle_g',oracle.g_used,'true_pair_gn1_rank',rank(q));disp(R);
end
