function Spectrum=Run_NoiseFreeCombinationSpectrum()
%RUN_NOISEFREECOMBINATIONSPECTRUM Dense-angle control for nonlinear orders.
% Avoids the rank deficiency of a global spectrum on BTT nonuniform samples.
root=fileparts(mfilename('fullpath'));mainDir=fileparts(root);addpath(mainDir,'-begin');addpath(fullfile(mainDir,'local_func'),'-begin');
ctx=load_inv_log_2_project_context(mainDir);tr=load_fixed_trust_domain(mainDir);lib=make_fixed_trust_template_library(ctx.gapList,ctx.xCell,ctx.yCell,NaN,ctx.cfgAna.xGridN,get_inv_log_2_model_def(),tr);base=make_inv_log_2_demo_case(ctx,.2);cfg=base.cfgCase;
g0=.50;delta=.10;A=[.25 .15];eo=[10 26];phi=[pi/4 -pi/3];T=repmat(eval_gap_template(lib,g0,lib.xGrid),1,numel(cfg.alpha_k));cal=struct('g0',g0,'mu',0,'tau',0,'zeta',1,'kappa',1,'b',0,'sensorIds',1:numel(cfg.alpha_k));model=build_path_template_model(lib,T,cal);gH=g0+delta;
sidGrid=ones(size(lib.xGrid));Fx=eval_gap_derivative(model,gH,lib.xGrid,sidGrid);[~,ix]=max(abs(Fx));x0=lib.xGrid(ix);fx0=Fx(ix);
n=16384;theta=(0:n-1)'*(2*pi/n);u=A(1)*sin(eo(1)*theta+phi(1))+A(2)*sin(eo(2)*theta+phi(2));sid=ones(n,1);V0=eval_gap_template(model,gH,x0*ones(n,1),sid);Vexact=eval_gap_template(model,gH,x0-u,sid)-V0;Vlinear=-fx0*u;
maxEO=40;exact=zeros(maxEO,1);linear=zeros(maxEO,1);for k=1:maxEO,s=sin(k*theta);c=cos(k*theta);exact(k)=hypot(2/n*(s'*Vexact),2/n*(c'*Vexact));linear(k)=hypot(2/n*(s'*Vlinear),2/n*(c'*Vlinear));end
Spectrum=table((1:maxEO)',exact,linear,'VariableNames',{'EO','exact_voltage_amplitude_V','linear_voltage_amplitude_V'});outDir=fullfile(root,'output','eo_combination_order_diagnostic');if ~exist(outDir,'dir'),mkdir(outDir);end;writetable(Spectrum,fullfile(outDir,'dense_angle_noiseless_order_spectrum.csv'));save(fullfile(outDir,'dense_angle_noiseless_order_spectrum.mat'),'Spectrum','x0','fx0','A','eo','phi');
fig=figure('Color','w','Units','centimeters','Position',[2 2 17 7]);tiledlayout(1,2,'TileSpacing','compact','Padding','compact');nexttile;bar(Spectrum.EO,1000*Spectrum.exact_voltage_amplitude_V,'FaceColor',[.2 .45 .75],'DisplayName','Exact nonlinear');hold on;plot(Spectrum.EO,1000*Spectrum.linear_voltage_amplitude_V,'r.-','LineWidth',1,'MarkerSize',7,'DisplayName','First-order linear');for e=[10 16 20 26],xline(e,'--','LineWidth',.8,'HandleVisibility','off');end;xlim([0 40]);xlabel('Engine order');ylabel('Voltage-order amplitude (mV)');legend('Location','best');box on;nexttile;semilogy(Spectrum.EO,max(1000*Spectrum.exact_voltage_amplitude_V,1e-8),'o-','LineWidth',1,'MarkerSize',3,'DisplayName','Exact nonlinear');hold on;semilogy(Spectrum.EO,max(1000*Spectrum.linear_voltage_amplitude_V,1e-8),'r.-','LineWidth',1,'MarkerSize',7,'DisplayName','First-order linear');for e=[10 16 20 26],xline(e,'--','LineWidth',.8,'HandleVisibility','off');end;xlim([0 40]);ylim([1e-5 1e2]);xlabel('Engine order');ylabel('Voltage-order amplitude (mV, log scale)');legend('Location','best');box on;set(findall(fig,'Type','axes'),'TickDir','in','FontName','Times New Roman','FontSize',8);exportgraphics(fig,fullfile(outDir,'dense_angle_noiseless_order_spectrum.png'),'Resolution',240);try,exportgraphics(fig,fullfile(outDir,'dense_angle_noiseless_order_spectrum.pdf'),'ContentType','vector');catch,end;disp(Spectrum(ismember(Spectrum.EO,[10 16 20 26]),:));
end
