function Result=Run_StructuredFourModeRegression(seedOffset)
if nargin<1,seedOffset=0;end
root=fileparts(mfilename('fullpath'));mainDir=fileparts(root);
addpath(mainDir,'-begin');addpath(fullfile(mainDir,'local_func'),'-begin');
ctx=load_inv_log_2_project_context(mainDir);tr=load_fixed_trust_domain(mainDir);
lib=make_fixed_trust_template_library(ctx.gapList,ctx.xCell,ctx.yCell,NaN,...
    ctx.cfgAna.xGridN,get_inv_log_2_model_def(),tr);
base=make_inv_log_2_demo_case(ctx,.2);cfg=configure_structured_identification(base.cfgCase,"experiment_current");
cfg.RPM_low=min(cfg.RPM_high,300);cfg.NumRevs_low=8;cfg.NumRevs_high=8;cfg.snrDb=5;
cfg.structuredMinRevolutions=8;fRot=cfg.RPM_high/60;
cases={...
 struct('mode',"single_sync",'gLow',.2,'gHigh',.8,'A',.10,'f',10*fRot,'eo',10),...
 struct('mode',"single_async",'gLow',.8,'gHigh',.5,'A',.15,'f',733,'eo',NaN),...
 struct('mode',"dual_sync_sync",'gLow',.8,'gHigh',.5,'A',[.25 .15],'f',[14 24]*fRot,'eo',[14 24]),...
 struct('mode',"dual_sync_async",'gLow',.5,'gHigh',.2,'A',[.25 .15],'f',[18*fRot 1383],'eo',18)};
rows=repmat(row0(),numel(cases),1);
minimumRevolutionGatePassed=test_minimum_revolution_gate(ctx,lib,cfg,seedOffset);
for i=1:numel(cases)
    c=cases{i};phi=[pi/4 -pi/3];phi=phi(1:numel(c.f));
    low=simulate_low_speed_template(@(z)eval_gap_template(lib,c.gLow,z),cfg,lib.domain,5,208000+i+seedOffset);
    d=simulate_rotating_waveform_from_template(@(z)eval_gap_template(lib,c.gHigh,z),...
        cfg.RPM_high,8,cfg.fs,cfg.R_tip,cfg.alpha_k,0,lib.domain,c.A,c.f,phi,'noise_ratio');
    sig=rms(d.V_clean-min(d.V_clean));rng(208100+i+seedOffset,'twister');d.V_cap=d.V_clean+sig/10^(5/20)*randn(size(d.V_clean));
    map=map_highspeed_to_space(d,cfg.alpha_k,cfg.R_tip,lib.domain,.02);
    ticCase=tic;fit=run_inv_log_2_structured_main(low,map,lib,cfg,c.mode);elapsed=toc(ticCase);
    if c.mode=="single_sync",ok=fit.eo_id==c.eo;
    elseif c.mode=="single_async",ok=abs(fit.f_id-c.f)<=1;
    elseif c.mode=="dual_sync_sync",ok=isequal(fit.eo_id,c.eo);
    else,ok=fit.sync_eo==c.eo&&abs(fit.async_frequency_hz-c.f(2))<=1;end
    ferr=max(abs(sort(fit.f_id)-sort(c.f)));
    rows(i)=struct('mode',c.mode,'max_frequency_error',ferr,'g_true',c.gHigh,...
        'g_est',fit.g_used,'rmse',fit.rmse,'elapsed_s',elapsed,...
        'used_samples',fit.used_sample_count,'observed_revolutions',fit.observed_revolutions,...
        'frequency_margin',fit.frequency_margin,'noise_normalized_margin',fit.noise_normalized_margin,...
        'identification_confident',fit.identification_confident,...
        'identification_status',fit.identification_status,...
        'requires_more_observations',fit.requires_more_observations,...
        'observation_action',fit.observation_action,...
        'competing_frequency_or_order',string(mat2str(fit.competing_frequency_or_order,7)),...
        'success',ok&&abs(fit.g_used-c.gHigh)<=.05&&fit.information_requirement_met);
end
Audit=struct2table(rows);out=fullfile(root,'output','structured_four_mode');
if seedOffset~=0,out=fullfile(root,'output',sprintf('structured_four_mode_seed_%d',seedOffset));end
if ~exist(out,'dir'),mkdir(out);end
writetable(Audit,fullfile(out,'structured_four_mode.csv'));save(fullfile(out,'structured_four_mode.mat'),'Audit');disp(Audit);
if ~all(Audit.success),error('Four-mode structured regression failed.');end
Result=struct('Audit',Audit,'minimumRevolutionGatePassed',minimumRevolutionGatePassed,'outputDir',out);
end
function r=row0()
r=struct('mode',"",'max_frequency_error',NaN,'g_true',NaN,'g_est',NaN,...
    'rmse',NaN,'elapsed_s',NaN,'used_samples',NaN,'observed_revolutions',NaN,...
    'frequency_margin',NaN,'noise_normalized_margin',NaN,...
    'identification_confident',false,'identification_status',"",...
    'requires_more_observations',false,...
    'observation_action',"",...
    'competing_frequency_or_order',"",'success',false);
end

function passed=test_minimum_revolution_gate(ctx,lib,cfg,seedOffset)
fRot=cfg.RPM_high/60;
low=simulate_low_speed_template(@(z)eval_gap_template(lib,.2,z),cfg,lib.domain,5,209001+seedOffset);
d=simulate_rotating_waveform_from_template(@(z)eval_gap_template(lib,.2,z),...
    cfg.RPM_high,4,cfg.fs,cfg.R_tip,cfg.alpha_k,0,lib.domain,.15,14*fRot,pi/4,'noise_ratio');
map=map_highspeed_to_space(d,cfg.alpha_k,cfg.R_tip,lib.domain,.02);
passed=false;
try
    run_inv_log_2_structured_main(low,map,lib,cfg,"single_sync");
catch ME
    passed=strcmp(ME.identifier,'invlog2:InsufficientRevolutions');
end
if ~passed,error('Four-revolution information gate did not reject the input.');end
end
