function Test_R5_StaticAuditRejectsMissingDomainMetadata()
% Formal gap models must not pass when calibration-domain metadata is absent.
m = struct('sensorId',1,'isGapSensor',true,'gapReferenceMm',1.2, ...
    'templateDomainMm',[0 1],'templateVoltageUnit','V', ...
    'coord',struct('responseScale',1,'responseTauMm',0,'responseOffsetMm',0), ...
    'templateEvaluate',@(x) double(x(:)), ...
    'evaluate',@local_evaluate);
a = R5_Audit_StaticObservationContract(m,{linspace(0,1,21).'},1e-8,0.8,false);
assert(~a.pass,'R5:MissingMetadataAccepted', ...
    'Formal static audit accepted a gap model without gap/response domains.');
assert(isfield(a.rows,'metadata_pass') && ~a.rows.metadata_pass, ...
    'R5:MissingMetadataStatus','Audit must expose the metadata failure.');
fprintf('Test_R5_StaticAuditRejectsMissingDomainMetadata PASS\n');
end

function [y,info]=local_evaluate(~,x)
x=double(x(:)); y=x;
info=struct('noGapMv',x,'xRegistered',x,'overshootXmm',zeros(size(x)), ...
    'overshootGapMm',zeros(size(x)),'overshootResponseXmm',zeros(size(x)));
end
