function Test_R5_StaticModelContracts()
%TEST_R5_STATICMODELCONTRACTS Regression checks for both frozen-state builders.
repo = fileparts(mfilename('fullpath'));
case27 = fullfile(repo,'20250527_gap_vibration_identification_v1','latest_programs_20260907');
case22 = fullfile(repo,'20251222_gap_vibration_identification_v1','latest_programs_20260905');
common = fullfile(repo,'common');
addpath(common,'-begin');

addpath(case27,'-begin');
c27 = Config_20250527();
assert(isequal(double(c27.frequency.searchHz),[300 1000]), ...
    'R5:FrequencyContract','20250527 search band changed.');
assert(~logical(c27.r5.useStaticGapSlopeInDynamic), ...
    'R5:StaticTiltContract','20250527 dynamic static-slope flag must be false.');
assert(strcmp(c27.r5.staticTiltCarrier,'absolute_surface_state'), ...
    'R5:StaticTiltContract','20250527 must use absolute frozen surface state.');
m27 = R5_Build_SensorConditionedDynamicModels_20250527( ...
    fullfile(c27.paths.results,'r5_sensor_conditioned_sidecar.mat'), ...
    c27.files.lowSpeedTemplate,c27.case.targetBlade);
assert(isequal(double([m27.sensorId]),double(c27.case.analysisSensors)), ...
    'R5:SensorOrder','20250527 model order must follow cfg.case.analysisSensors.');
check_models(m27,'20250527');
rmpath(case27);
clear Config_20250527 R5_Build_SensorConditionedDynamicModels_20250527

addpath(case22,'-begin');
c22 = Config_20251222();
assert(isequal(double(c22.frequency.searchHz),[300 1000]), ...
    'R5:FrequencyContract','20251222 search band changed.');
assert(~logical(c22.r5.useStaticGapSlopeInDynamic), ...
    'R5:StaticTiltContract','20251222 dynamic static-slope flag must be false.');
assert(strcmp(c22.r5.staticTiltCarrier,'absolute_surface_state'), ...
    'R5:StaticTiltContract','20251222 must use absolute frozen surface state.');
m22 = R5_Build_SensorConditionedDynamicModels_20251222( ...
    fullfile(c22.paths.results,'R5_SensorConditionedSidecar_B1_S123.mat'), ...
    c22.files.lowSpeedTemplate,1);
assert(isequal(double([m22.sensorId]),double(c22.case.analysisSensors)), ...
    'R5:SensorOrder','20251222 model order must follow cfg.case.analysisSensors.');
check_models(m22,'20251222');

fprintf('Test_R5_StaticModelContracts PASS\n');
end

function check_models(models,label)
required = {'gapDomainMm','responseDomainMm','templateDomainMm','coord'};
for k=1:numel(models)
    for j=1:numel(required)
        assert(isfield(models(k),required{j}), 'R5:DomainMetadata', ...
            '%s S%d lacks %s.',label,models(k).sensorId,required{j});
    end
    assert(all(isfinite(models(k).gapDomainMm)) && ...
        models(k).gapReferenceMm>=models(k).gapDomainMm(1) && ...
        models(k).gapReferenceMm<=models(k).gapDomainMm(2), ...
        'R5:GapDomain','%s S%d g0 is outside the calibration domain.', ...
        label,models(k).sensorId);
    assert(all(isfinite(models(k).responseDomainMm)), ...
        'R5:ResponseDomain','%s S%d lacks a finite response domain.', ...
        label,models(k).sensorId);
end
end
