function out = Plot_R4_Fig4_GeometryMismatch_v14()
% Fig. 4 | Geometry-mismatch response-surface transfer
% v14 - replace the legacy C1/C2 panel with the transferred-surface
% dynamic validation; keep the visible MATLAB figure open for review.
% a : calibration/rotor relative-geometry schematic
% b : complete FE waveform family
% c : geometry-induced response difference
% d : blind cross-gap transfer NRMSE
% e : representative blind-transfer waveforms
% f : downstream dynamic residual after surface transfer

root = fileparts(mfilename('fullpath'));

r4 = fullfile( ...
    fileparts(fileparts(root)), ...
    'r4_pc1_manifold_transfer', ...
    'output');

od = root;

if ~exist(od,'dir')
    mkdir(od);
end

raw = load(fullfile( ...
    r4, ...
    'waveform_families', ...
    'TiltGap_WaveformSurfaceData.mat'));

D = raw.Data;

x      = D.x_mm(:);
g      = D.gap_mm(:);
states = D.tilt_deg(:);
V      = D.response_V;

loc = readtable(fullfile( ...
    r4, ...
    'surface_identification_gap_law', ...
    'predicted_family_localization_per_anchor.csv'));

dyn = readtable(fullfile( ...
    r4, ...
    'transferred_surface_dynamic_validation', ...
    'transferred_surface_dynamic_results.csv'));

set(groot, ...
    'defaultAxesFontName','Arial', ...
    'defaultTextFontName','Arial', ...
    'defaultAxesFontSize',6.5, ...
    'defaultAxesLineWidth',0.55, ...
    'defaultLineLineWidth',0.8);

blue       = [0.000 0.447 0.741];
vermillion = [0.850 0.325 0.098];
teal       = [0.000 0.550 0.500];

dark = [0.16 0.16 0.16];
grey = [0.42 0.42 0.42];

gapCols = [ ...
    0.92 0.63 0.08
    0.72 0.68 0.16
    0.38 0.66 0.38
    0.08 0.55 0.49
    0.06 0.38 0.56
    0.22 0.18 0.42];

nS = numel(states);
nG = numel(g);

vLim = [min(V(:)),max(V(:))];

f = figure( ...
    'Color','w', ...
    'Units','centimeters', ...
    'Position',[2 2 18.3 14.2], ...
    'Renderer','painters');

%% ========================================================================
% a | Physical schematic
% =========================================================================

axA = axes( ...
    'Parent',f, ...
    'Position',[ ...
    0.018 ...
    0.535 ...
    0.360 ...
    0.445]);

drawPanelA( ...
    axA, ...
    blue,vermillion,dark,grey);

%% ========================================================================
% b | Complete FE waveform family
% =========================================================================

annotation(f,'textbox', ...
    [0.390 0.944 0.020 0.020], ...
    'String','b', ...
    'LineStyle','none', ...
    'FontName','Arial', ...
    'FontSize',8, ...
    'FontWeight','bold');

pL  = 0.405;
pB  = 0.795;

pW  = 0.123;
pH  = 0.112;

pGX = 0.008;
pGY = 0.075;

for k = 1:nS

    row = 1 + (k > 4);
    col = k - 4*(row-1);

    px = pL + (col-1)*(pW+pGX);
    py = pB - (row-1)*(pH+pGY);

    ax = axes( ...
        'Parent',f, ...
        'Position',[px py pW pH]);

    hold(ax,'on');

    for j = 1:nG

        plot(ax, ...
            x, ...
            V(:,j,k), ...
            'Color',gapCols(j,:), ...
            'LineWidth',0.82);

    end

    xlim(ax,[min(x) max(x)]);

    ylim(ax,[ ...
        vLim(1) ...
        vLim(2)+0.045]);

    set(ax, ...
        'FontSize',5.6, ...
        'LineWidth',0.50, ...
        'TickDir','out', ...
        'Box','off', ...
        'XTick',[-5 0 5], ...
        'YTick',[0.15 0.25 0.35]);

    stateLabel = [ ...
        num2str(states(k),'%.1f') ...
        char(176)];

    title(ax, ...
        stateLabel, ...
        'FontSize',6.3, ...
        'FontWeight','normal');

    if row == 2

        xlabel(ax, ...
            '\it x\rm (mm)', ...
            'FontSize',6.5);

    else

        ax.XTickLabel = [];

    end

    if col == 1

        ylabel(ax, ...
            '\it V\rm (V)', ...
            'FontSize',6.5);

    else

        ax.YTickLabel = [];

    end

end

%% ------------------------------------------------------------------------
% b legend
% -------------------------------------------------------------------------

axBL = axes( ...
    'Parent',f, ...
    'Position',[ ...
    pL+3*(pW+pGX), ...
    pB-(pH+pGY), ...
    pW, ...
    pH]);

axis(axBL,[0 1 0 1]);
axis(axBL,'off');
hold(axBL,'on');

text(axBL, ...
    0.50,0.91, ...
    'g (mm)', ...
    'HorizontalAlignment','center', ...
    'FontWeight','bold', ...
    'FontSize',6.3);

for j = 1:nG

    cc = 1 + (j>3);
    rr = j - 3*(cc-1);

    x0 = 0.06 + 0.50*(cc-1);
    y0 = 0.66 - 0.25*(rr-1);

    plot(axBL, ...
        [x0 x0+0.18], ...
        [y0 y0], ...
        'Color',gapCols(j,:), ...
        'LineWidth',1.35);

    text(axBL, ...
        x0+0.23, ...
        y0, ...
        sprintf('%.2f',g(j)), ...
        'FontSize',5.9, ...
        'VerticalAlignment','middle');

end

%% ========================================================================
% Lower row
% =========================================================================

panelLetterY = 0.480;

headerY = 0.457;
headerH = 0.012;

%% ========================================================================
% c
% =========================================================================

cPos = [ ...
    0.050 ...
    0.105 ...
    0.195 ...
    0.335];

axC = axes( ...
    'Parent',f, ...
    'Position',cPos);

hold(axC,'on');

addPanelLetter( ...
    f,'c', ...
    0.028,panelLetterY);

delta = squeeze( ...
    V(:,:,end)-V(:,:,1));

imagesc(axC,x,g,delta');

axis(axC,'xy');

ylim(axC,[min(g) max(g)]);

lim = max(abs(delta(:)));

clim(axC,[-lim lim]);

colormap(axC,blueWhiteRed(256));

set(axC, ...
    'YTick',g, ...
    'FontSize',6.25, ...
    'TickDir','out', ...
    'Box','off');

xlabel(axC, ...
    '\it x\rm (mm)', ...
    'FontSize',7);

ylabel(axC, ...
    '\it g\rm (mm)', ...
    'FontSize',7);

text(axC, ...
    0.03,0.96, ...
    '3.5\circ - 0.5\circ', ...
    'Units','normalized', ...
    'FontSize',6, ...
    'VerticalAlignment','top', ...
    'BackgroundColor','w', ...
    'Margin',1);

cbC = colorbar(axC,'northoutside');

cbC.Position = [ ...
    0.050 ...
    headerY ...
    0.195 ...
    headerH];

cbC.FontSize = 5.5;

cbC.Ticks = [-lim 0 lim];

cbC.TickLabels = compose( ...
    '%.3f', ...
    [-lim 0 lim]);

cbC.Label.String = ...
    '\Delta V_{geom} (V)';

cbC.Label.FontSize = 6.5;

%% ========================================================================
% d
% =========================================================================

dPos = [ ...
    0.305 ...
    0.105 ...
    0.205 ...
    0.335];

axD = axes( ...
    'Parent',f, ...
    'Position',dPos);

addPanelLetter( ...
    f,'d', ...
    0.280,panelLetterY);

E = nan(nS,nG);

for is = 1:nS

    for ig = 1:nG

        q = ...
            abs(loc.targetTilt-states(is)) < 1e-12 & ...
            abs(loc.anchorGap-g(ig))       < 1e-12;

        if nnz(q) == 1

            E(is,ig) = ...
                loc.transferNrmsePct(q);

        end

    end

end

imagesc(axD,g,states,E);

axis(axD,'xy');

colormap(axD,transferMap(256));

set(axD, ...
    'XTick',g, ...
    'YTick',states, ...
    'FontSize',6, ...
    'TickDir','out', ...
    'Box','off');

xlabel(axD, ...
    'adaptation clearance, \it g_a\rm (mm)', ...
    'FontSize',7);

ylabel(axD, ...
    'held-out geometry configuration (\circ)', ...
    'FontSize',7);

cbD = colorbar(axD,'northoutside');

cbD.Position = [ ...
    0.305 ...
    headerY ...
    0.205 ...
    headerH];

cbD.FontSize = 5.5;

cbD.Ticks = [0.10 0.40];

cbD.TickLabels = { ...
    '0.10','0.40'};

cbD.Label.String = ...
    'cross-gap NRMSE (%)';

cbD.Label.FontSize = 6.5;

validE = E(~isnan(E));

if isempty(validE)
    mxE = 1;
else
    mxE = max(validE);
end

for is = 1:nS

    for ig = 1:nG

        if isnan(E(is,ig))
            continue;
        end

        if E(is,ig) > 0.72*mxE
            tc = 'w';
        else
            tc = dark;
        end

        text(axD, ...
            g(ig), ...
            states(is), ...
            sprintf('%.2f',E(is,ig)), ...
            'HorizontalAlignment','center', ...
            'FontSize',4.9, ...
            'Color',tc);

    end

end

%% ========================================================================
% e
% =========================================================================

addPanelLetter( ...
    f,'e', ...
    0.535,panelLetterY);

eTopPos = [ ...
    0.565 ...
    0.295 ...
    0.165 ...
    0.145];

eBotPos = [ ...
    0.565 ...
    0.105 ...
    0.165 ...
    0.145];

ePos = { ...
    eTopPos, ...
    eBotPos};

anchorIndex = ...
    find(abs(g-1.10)<1e-12,1);

for ic = 1:2

    if ic == 1
        it = 1;
    else
        it = nS;
    end

    pred = blindPrediction( ...
        V,g,it,anchorIndex);

    axE = axes( ...
        'Parent',f, ...
        'Position',ePos{ic});

    hold(axE,'on');

    plot(axE, ...
        x, ...
        V(:,anchorIndex,it), ...
        'Color',blue, ...
        'LineWidth',1.05);

    edgeGaps = [1 nG];

    for jj = edgeGaps

        plot(axE, ...
            x, ...
            V(:,jj,it), ...
            'Color',dark, ...
            'LineWidth',0.78);

        plot(axE, ...
            x, ...
            pred(:,jj), ...
            '--', ...
            'Color',vermillion, ...
            'LineWidth',0.92);

    end

    xlim(axE,[min(x) max(x)]);

    ylim(axE,[ ...
        vLim(1) ...
        vLim(2)+0.035]);

    set(axE, ...
        'FontSize',5.8, ...
        'TickDir','out', ...
        'Box','off', ...
        'XTick',[-5 0 5], ...
        'YTick',[0.15 0.25 0.35]);

    text(axE, ...
        0.045,0.91, ...
        ['\Delta\alpha = ' ...
        num2str(states(it),'%.1f') ...
        '^\circ'], ...
        'Units','normalized', ...
        'Interpreter','tex', ...
        'FontSize',6, ...
        'VerticalAlignment','top');

    if ic == 1

        axE.XTickLabel = [];

    else

        xlabel(axE, ...
            '\it x\rm (mm)', ...
            'FontSize',7);

    end

end

axEY = axes( ...
    'Parent',f, ...
    'Position',[ ...
    0.510 ...
    0.105 ...
    0.018 ...
    0.335]);

axis(axEY,[0 1 0 1]);
axis(axEY,'off');

text(axEY, ...
    0.50,0.50, ...
    '\it V\rm (V)', ...
    'Interpreter','tex', ...
    'Rotation',90, ...
    'FontSize',7, ...
    'Color',dark, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle');

axEL = axes( ...
    'Parent',f, ...
    'Position',[ ...
    0.565 ...
    0.455 ...
    0.165 ...
    0.025]);

axis(axEL,[0 1 0 1]);
axis(axEL,'off');
hold(axEL,'on');

legendX = [ ...
    0.00 ...
    0.35 ...
    0.67];

legendNames = { ...
    'adaptation', ...
    'target FE', ...
    'adapted prediction'};

legendCols = { ...
    blue, ...
    dark, ...
    vermillion};

legendStyles = { ...
    '-', ...
    '-', ...
    '--'};

for k = 1:3

    plot(axEL, ...
        [legendX(k) legendX(k)+0.11], ...
        [0.50 0.50], ...
        legendStyles{k}, ...
        'Color',legendCols{k}, ...
        'LineWidth',1.05);

    text(axEL, ...
        legendX(k)+0.14, ...
        0.50, ...
        legendNames{k}, ...
        'FontSize',5.3, ...
        'VerticalAlignment','middle');

end

%% ========================================================================
% f
% =========================================================================

fPos = [ ...
    0.785 ...
    0.105 ...
    0.175 ...
    0.335];

addPanelLetter( ...
    f,'f', ...
    0.758,panelLetterY);

axF = axes( ...
    'Parent',f, ...
    'Position',fPos);

hold(axF,'on');

method = string(dyn.method);
names = ["common_reference" "anchor_transferred" "FE_oracle"];
labels = {'common calibration','adapted','target FE ref.'};
cols = {vermillion, teal, grey};
marks = {'o','s','d'};
offsets = [-0.055 0 0.055];

for jm = 1:numel(names)

    q = method == names(jm);

    plot(axF, ...
        dyn.tilt_deg(q)+offsets(jm), ...
        dyn.fit_rmse_V(q), ...
        marks{jm}, ...
        'LineStyle','none', ...
        'Color',cols{jm}, ...
        'MarkerFaceColor','none', ...
        'MarkerSize',4.0, ...
        'LineWidth',0.78);

    med = nan(nS,1);

    for is = 1:nS

        rr = ...
            q & abs(dyn.tilt_deg-states(is)) < 1e-12;

        if any(rr)

            med(is) = ...
                median(dyn.fit_rmse_V(rr));

        end

    end

    plot(axF, ...
        states+offsets(jm), ...
        med, ...
        '-', ...
        'Color',cols{jm}, ...
        'LineWidth',0.72);

end

xlim(axF,[0.30 3.70]);

set(axF, ...
    'XTick',states, ...
    'YScale','log', ...
    'YLim',[8e-7 2e-3], ...
    'YTick',[1e-6 1e-5 1e-4 1e-3], ...
    'FontSize',6, ...
    'TickDir','out', ...
    'Box','off');

xlabel(axF, ...
    'held-out geometry configuration (\circ)', ...
    'FontSize',7);

ylabel(axF, ...
    'dynamic fit RMSE (V)', ...
    'FontSize',7);

axFL = axes( ...
    'Parent',f, ...
    'Position',[ ...
    0.785 ...
    0.455 ...
    0.175 ...
    0.025]);

axis(axFL,[0 1 0 1]);
axis(axFL,'off');
hold(axFL,'on');

fx = [0.01 0.34 0.70];

for jm = 1:3

    plot(axFL, ...
        fx(jm),0.50, ...
        marks{jm}, ...
        'LineStyle','none', ...
        'Color',cols{jm}, ...
        'MarkerFaceColor','none', ...
        'MarkerSize',4.0, ...
        'LineWidth',0.80);

    text(axFL, ...
        fx(jm)+0.065, ...
        0.50, ...
        labels{jm}, ...
        'FontSize',5.0, ...
        'VerticalAlignment','middle');

end

%% ========================================================================
% Export
% =========================================================================

base = fullfile( ...
    od, ...
    'Fig4_R4_GeometryMismatchTransfer_v14');

print(f, ...
    [base '.svg'], ...
    '-dsvg');

if exist('exportgraphics','file') == 2

    exportgraphics( ...
        f, ...
        [base '.pdf'], ...
        'ContentType','vector');

    exportgraphics( ...
        f, ...
        [base '.png'], ...
        'Resolution',600);

else

    print(f, ...
        [base '.pdf'], ...
        '-dpdf', ...
        '-painters');

    print(f, ...
        [base '.png'], ...
        '-dpng', ...
        '-r600');

end

out = struct();

out.figure = f;
out.svg = [base '.svg'];
out.pdf = [base '.pdf'];
out.png = [base '.png'];

end


%% ========================================================================
% Lower-row panel letter helper
% =========================================================================

function addPanelLetter(f,letter,x,y)

annotation(f,'textbox', ...
    [x y 0.020 0.020], ...
    'String',letter, ...
    'LineStyle','none', ...
    'Margin',0, ...
    'FontName','Arial', ...
    'FontSize',8, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','middle');

end


%% ========================================================================
% PANEL A
% =========================================================================

function drawPanelA(ax,blue,orange,dark,grey)

cla(ax);
hold(ax,'on');

axis(ax,[0 1 0 1]);
axis(ax,'equal');
axis(ax,'off');

darkGrey  = [0.38 0.38 0.38];
midGrey   = [0.64 0.66 0.68];
lightGrey = [0.94 0.945 0.95];

diskFill = [0.90 0.92 0.93];

targetFill = [0.72 0.76 0.79];
targetEdge = [0.18 0.20 0.22];

neighFill = [0.92 0.93 0.94];
neighEdge = [0.72 0.74 0.76];

refGrey = [0.73 0.73 0.73];

xCal = 0.25;
xRot = 0.75;

ySensorR3 = 0.855;
ySensorR4 = 0.350;

% --------------------------------------------------------------
% Only graphical objects in panel a are enlarged.
% ALL text FontSize settings below remain exactly unchanged.
% --------------------------------------------------------------

shapeScale = 1.18;

bladeScale = 0.075 * shapeScale;

% Slightly reduce the empty clearance so enlarged graphics fit
% without changing any text positions or font sizes.
gapLength = 0.033;

sensorTiltR4 = 2.5;

% Keep approximately the same visual mismatch after rotor enlargement.
centreShiftR4 = 0.012 * shapeScale;

%% Panel letter

text(ax, ...
    0.012,0.987, ...
    'a', ...
    'FontSize',8, ...
    'FontWeight','bold', ...
    'Color',dark, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top');

%% Column titles

text(ax, ...
    xCal,0.955, ...
    'calibration', ...
    'FontSize',6.0, ...
    'Color',darkGrey, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle');

text(ax, ...
    xRot,0.955, ...
    'rotor', ...
    'FontSize',6.0, ...
    'Color',darkGrey, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle');

%% Divider

plot(ax, ...
    [0.04 0.96], ...
    [0.493 0.493], ...
    '-', ...
    'Color',[0.89 0.89 0.89], ...
    'LineWidth',0.55);

%% Top row

drawRigA( ...
    ax,xCal,ySensorR3, ...
    0,0, ...
    bladeScale,gapLength,shapeScale, ...
    true,false, ...
    blue,orange,darkGrey,midGrey,lightGrey, ...
    diskFill,targetFill,targetEdge, ...
    neighFill,neighEdge,refGrey);

drawRigA( ...
    ax,xRot,ySensorR3, ...
    0,0, ...
    bladeScale,gapLength,shapeScale, ...
    false,false, ...
    blue,orange,darkGrey,midGrey,lightGrey, ...
    diskFill,targetFill,targetEdge, ...
    neighFill,neighEdge,refGrey);

%% Bottom row

drawRigA( ...
    ax,xCal,ySensorR4, ...
    0,0, ...
    bladeScale,gapLength,shapeScale, ...
    false,false, ...
    blue,orange,darkGrey,midGrey,lightGrey, ...
    diskFill,targetFill,targetEdge, ...
    neighFill,neighEdge,refGrey);

drawRigA( ...
    ax,xRot,ySensorR4, ...
    sensorTiltR4, ...
    centreShiftR4, ...
    bladeScale,gapLength,shapeScale, ...
    false,true, ...
    blue,orange,darkGrey,midGrey,lightGrey, ...
    diskFill,targetFill,targetEdge, ...
    neighFill,neighEdge,refGrey);

%% Text: unchanged size

text(ax, ...
    xCal,ySensorR3+0.064, ...
    'sensor', ...
    'FontSize',5.3, ...
    'Color',grey, ...
    'HorizontalAlignment','center');

text(ax, ...
    0.505,0.540, ...
    'F_{cal} \approx F_{rotor}', ...
    'Interpreter','tex', ...
    'FontSize',6.1, ...
    'Color',darkGrey, ...
    'HorizontalAlignment','center');

text(ax, ...
    0.505,0.105, ...
    'F_{cal} \neq F_{rotor}', ...
    'Interpreter','tex', ...
    'FontSize',6.1, ...
    'Color',darkGrey, ...
    'HorizontalAlignment','center');

end


%% ========================================================================
% Complete rig
% =========================================================================

function G = drawRigA( ...
    ax,cx,mountY, ...
    sensorTiltDeg,centreShiftX, ...
    bladeScale,gapLength,shapeScale, ...
    showGap,showMismatch, ...
    blue,orange,darkGrey,midGrey,lightGrey, ...
    diskFill,targetFill,targetEdge, ...
    neighFill,neighEdge,refGrey)

Rtip = 1.95;

RtipPlot = Rtip*bladeScale;

S = drawSensorA( ...
    ax,cx,mountY,sensorTiltDeg,shapeScale, ...
    blue,darkGrey,midGrey,lightGrey);

tip = ...
    S.faceCentre + ...
    gapLength*S.senseDir;

centreRef = ...
    tip + ...
    RtipPlot*S.senseDir;

centreX = ...
    centreRef(1) + ...
    centreShiftX;

dx = ...
    centreX-tip(1);

if abs(dx) >= RtipPlot

    error( ...
        'Panel-a centre shift exceeds rotor radius.');

end

dy = ...
    sqrt(RtipPlot^2-dx^2);

centre = [ ...
    centreX
    tip(2)-dy];

outwardRadial = ...
    (tip-centre)/RtipPlot;

inwardRadial = ...
    -outwardRadial;

betaTarget = ...
    atan2d( ...
    outwardRadial(2), ...
    outwardRadial(1));

drawRotorAssemblyA( ...
    ax,centre,betaTarget,bladeScale, ...
    diskFill,targetFill,targetEdge, ...
    neighFill,neighEdge,midGrey);

%% Rotor centre marker: graphical element, enlarged

plot(ax, ...
    centre(1),centre(2), ...
    '.', ...
    'Color',darkGrey, ...
    'MarkerSize',6*shapeScale);

%% Clearance g
if showGap

    % -------------------------------------------------------------
    % Physical endpoints:
    % upper = sensor sensing face
    % lower = measured blade tip
    % -------------------------------------------------------------

    yTop = S.faceCentre(2);
    yBot = tip(2);

    % Keep the dimension arrow inside the actual sensor-tip gap.
    % Only a small lateral offset is used to avoid covering
    % the central sensing axis / blade.
    xGap = S.faceCentre(1) - 0.030;

    % Small inward padding so arrowheads do not visually touch
    % the sensor face / blade-tip contour.
    pad = 0.0035;

    y1 = yTop - pad;
    y2 = yBot + pad;


    %% ------------------------------------------------------------
    % Short witness / extension lines
    % These explicitly connect the dimension to the physical
    % sensor face and blade tip.
    % -------------------------------------------------------------

    guideCol = [0.55 0.55 0.55];

    % sensor-face guide
    plot(ax, ...
        [xGap+0.004 S.faceCentre(1)-0.004], ...
        [yTop yTop], ...
        '-', ...
        'Color',guideCol, ...
        'LineWidth',0.45);

    % blade-tip guide
    plot(ax, ...
        [xGap+0.004 tip(1)-0.004], ...
        [yBot yBot], ...
        '-', ...
        'Color',guideCol, ...
        'LineWidth',0.45);


    %% ------------------------------------------------------------
    % Double arrow
    % -------------------------------------------------------------

    drawDoubleArrowA( ...
        ax,xGap,y1,y2,darkGrey, ...
        0.0048*shapeScale, ...
        0.0038*shapeScale, ...
        0.55);


    %% ------------------------------------------------------------
    % g label
    %
    % Only move the TEXT to the left.
    % Do not move the physical dimension itself.
    % -------------------------------------------------------------

    text(ax, ...
        xGap-0.018, ...
        (yTop+yBot)/2, ...
        'g', ...
        'FontSize',5.8, ...
        'FontAngle','italic', ...
        'Color',darkGrey, ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle');

end


%% Relative geometry mismatch

if showMismatch

    plot(ax, ...
        [S.faceCentre(1) tip(1)], ...
        [S.faceCentre(2) tip(2)], ...
        '--', ...
        'Color',blue, ...
        'LineWidth',0.72);

    plot(ax, ...
        [tip(1) centre(1)], ...
        [tip(2) centre(2)], ...
        '--', ...
        'Color',darkGrey, ...
        'LineWidth',0.68);

    plot(ax, ...
        centreRef(1),centreRef(2), ...
        'o', ...
        'MarkerSize',3.2*shapeScale, ...
        'MarkerFaceColor','w', ...
        'MarkerEdgeColor',refGrey, ...
        'LineWidth',0.60);

    plot(ax, ...
        [centreRef(1) centre(1)], ...
        [centreRef(2) centre(2)], ...
        ':', ...
        'Color',refGrey, ...
        'LineWidth',0.60);

    drawVectorAngleA( ...
        ax,tip, ...
        S.senseDir, ...
        inwardRadial, ...
        0.025*shapeScale,orange);

    a1 = ...
        atan2d( ...
        S.senseDir(2), ...
        S.senseDir(1));

    a2 = ...
        atan2d( ...
        inwardRadial(2), ...
        inwardRadial(1));

    da = ...
        wrapTo180Local(a2-a1);

    amid = ...
        a1 + da/2;

    labelPos = ...
        tip + ...
        (0.045*shapeScale)*[ ...
        cosd(amid)
        sind(amid)];

    % FontSize intentionally unchanged
    text(ax, ...
        labelPos(1)+0.007, ...
        labelPos(2), ...
        '\Delta\alpha', ...
        'Interpreter','tex', ...
        'FontSize',5.8, ...
        'FontWeight','bold', ...
        'Color',orange, ...
        'HorizontalAlignment','left', ...
        'VerticalAlignment','middle');

end

G.sensorFace = S.faceCentre;
G.tip = tip;
G.referenceCentre = centreRef;
G.actualCentre = centre;

end


%% ========================================================================
% Sensor / casing graphics
% =========================================================================

function S = drawSensorA( ...
    ax,cx,mountY,tiltDeg,shapeScale, ...
    blue,darkGrey,midGrey,lightGrey)

%% Casing

halfW = 0.120 * shapeScale;

xc = linspace( ...
    cx-halfW, ...
    cx+halfW, ...
    150);

yc = ...
    mountY ...
    - (0.006*shapeScale)* ...
    ((xc-cx)/halfW).^2;

plot(ax,xc,yc, ...
    'Color',midGrey, ...
    'LineWidth',0.65);

%% Sensor rotation

th = ...
    tiltDeg*pi/180;

R = [ ...
    cos(th) -sin(th)
    sin(th)  cos(th)];

pivot = [ ...
    cx
    mountY];

%% Housing

housingW = ...
    0.067*shapeScale;

P = [ ...
    -housingW/2 ...
     housingW/2 ...
     housingW/2 ...
    -housingW/2
     0.003*shapeScale ...
     0.003*shapeScale ...
     0.039*shapeScale ...
     0.039*shapeScale];

P = R*P;

P(1,:) = ...
    P(1,:) + pivot(1);

P(2,:) = ...
    P(2,:) + pivot(2);

patch(ax, ...
    P(1,:),P(2,:), ...
    lightGrey, ...
    'EdgeColor',darkGrey, ...
    'LineWidth',0.55);

%% Probe

probeW = ...
    0.018*shapeScale;

Q = [ ...
    -probeW/2 ...
     probeW/2 ...
     probeW/2 ...
    -probeW/2
    -0.014*shapeScale ...
    -0.014*shapeScale ...
     0.008*shapeScale ...
     0.008*shapeScale];

Q = R*Q;

Q(1,:) = ...
    Q(1,:) + pivot(1);

Q(2,:) = ...
    Q(2,:) + pivot(2);

patch(ax, ...
    Q(1,:),Q(2,:), ...
    blue, ...
    'EdgeColor','none');

%% Sensing face

F = [ ...
    -probeW*0.65 ...
     probeW*0.65
    -0.014*shapeScale ...
    -0.014*shapeScale];

F = R*F;

F(1,:) = ...
    F(1,:) + pivot(1);

F(2,:) = ...
    F(2,:) + pivot(2);

plot(ax, ...
    F(1,:),F(2,:), ...
    'Color',blue, ...
    'LineWidth',0.92);

faceCentre = ...
    mean(F,2);

senseDir = ...
    R*[0;-1];

senseDir = ...
    senseDir/norm(senseDir);

S.faceCentre = faceCentre;
S.senseDir = senseDir;

end


%% ========================================================================
% Rotor assembly
% =========================================================================

function drawRotorAssemblyA( ...
    ax,centre,betaTarget,bladeScale, ...
    diskFill,targetFill,targetEdge, ...
    neighFill,neighEdge,midGrey)

Nb = 15;

pitchDeg = ...
    360/Nb;

%% Neighbour blades

for kk = [-2 -1 1 2]

    beta = ...
        betaTarget + ...
        kk*pitchDeg;

    drawImpellerBladeA( ...
        ax,centre,beta,bladeScale, ...
        neighFill,neighEdge,0.42);

end

%% Target blade

drawImpellerBladeA( ...
    ax,centre,betaTarget,bladeScale, ...
    targetFill,targetEdge,0.72);

%% Rotor disk

Rhub = 1.00;

diskR = ...
    0.98*Rhub*bladeScale;

phi = ...
    linspace(0,2*pi,200);

fill(ax, ...
    centre(1)+diskR*cos(phi), ...
    centre(2)+diskR*sin(phi), ...
    diskFill, ...
    'EdgeColor',midGrey, ...
    'LineWidth',0.55);

end


%% ========================================================================
% One curved blade
% =========================================================================

function drawImpellerBladeA( ...
    ax,centre,betaDeg,bladeScale, ...
    faceColor,edgeColor,lineWidth)

[xb,yb,tipAngle] = ...
    originalImpellerBladeA();

beta = ...
    betaDeg*pi/180;

rotationAngle = ...
    beta-tipAngle;

R = [ ...
    cos(rotationAngle) -sin(rotationAngle)
    sin(rotationAngle)  cos(rotationAngle)];

XY = ...
    R*[xb;yb];

XY = ...
    bladeScale*XY;

XY(1,:) = ...
    XY(1,:) + centre(1);

XY(2,:) = ...
    XY(2,:) + centre(2);

patch(ax, ...
    XY(1,:),XY(2,:), ...
    faceColor, ...
    'EdgeColor',edgeColor, ...
    'LineWidth',lineWidth);

end


%% ========================================================================
% Original curved blade geometry
% =========================================================================

function [xb,yb,tipAngle] = ...
    originalImpellerBladeA()

Rhub = 1.00;
Rtip = 1.95;

theta0 = ...
    5*pi/180;

sweep = ...
    38*pi/180;

wRoot = ...
    2.5*pi/180;

wMax = ...
    5.0*pi/180;

t = ...
    linspace(0,1,220);

r = ...
    Rhub + ...
    (Rtip-Rhub).*t;

theta_c = ...
    theta0 + ...
    sweep.*t.^1.15;

width = ...
    wRoot.*(1-t) + ...
    wMax.*sin(pi*t).^0.9;

theta1 = ...
    theta_c + width;

theta2 = ...
    theta_c - width;

x1 = ...
    r.*cos(theta1);

y1 = ...
    r.*sin(theta1);

x2 = ...
    r.*cos(theta2);

y2 = ...
    r.*sin(theta2);

xb = [ ...
    x1 ...
    fliplr(x2)];

yb = [ ...
    y1 ...
    fliplr(y2)];

tipAngle = ...
    theta0+sweep;

end


%% ========================================================================
% Double arrow
% =========================================================================

function drawDoubleArrowA( ...
    ax,x,yTop,yBottom,col, ...
    headLength,headWidth,lineWidth)

plot(ax, ...
    [x x], ...
    [yBottom yTop], ...
    'Color',col, ...
    'LineWidth',lineWidth);

patch(ax, ...
    [ ...
    x-headWidth/2 ...
    x+headWidth/2 ...
    x], ...
    [ ...
    yTop-headLength ...
    yTop-headLength ...
    yTop], ...
    col, ...
    'EdgeColor',col);

patch(ax, ...
    [ ...
    x-headWidth/2 ...
    x+headWidth/2 ...
    x], ...
    [ ...
    yBottom+headLength ...
    yBottom+headLength ...
    yBottom], ...
    col, ...
    'EdgeColor',col);

end


%% ========================================================================
% Angle arc
% =========================================================================

function drawVectorAngleA( ...
    ax,origin,v1,v2,r,col)

a1 = ...
    atan2d(v1(2),v1(1));

a2 = ...
    atan2d(v2(2),v2(1));

da = ...
    wrapTo180Local(a2-a1);

theta = ...
    linspace(a1,a1+da,60);

xx = ...
    origin(1) + ...
    r*cosd(theta);

yy = ...
    origin(2) + ...
    r*sind(theta);

plot(ax,xx,yy, ...
    'Color',col, ...
    'LineWidth',0.85);

end


%% ========================================================================
% Blind transfer prediction
% =========================================================================

function pred = blindPrediction( ...
    V,g,targetIndex,anchorIndex)

[nX,nG,nS] = ...
    size(V);

gref = 0.8;

X = [ ...
    ones(nG,1), ...
    1./g, ...
    log(g/gref)];

train = ...
    setdiff(1:nS,targetIndex);

Q = zeros( ...
    3*nX, ...
    numel(train));

for k = 1:numel(train)

    B = ...
        (X\V(:,:,train(k)).').';

    Q(:,k) = ...
        B(:);

end

mu = ...
    mean(Q,2);

[U,~,~] = ...
    svd(Q-mu,'econ');

Ur = ...
    U(:,1:min(2,size(U,2)));

Z = ...
    Ur'*(Q-mu);

[z1,ord] = ...
    sort(Z(1,:),'ascend');

Qord = ...
    Q(:,ord);

dz = ...
    max(diff(z1));

tgrid = ...
    linspace( ...
    z1(1)-0.5*dz, ...
    z1(end)+0.5*dz, ...
    401);

y = ...
    V(:,anchorIndex,targetIndex);

dist = ...
    nan(size(tgrid));

for k = 1:numel(tgrid)

    q = interp1( ...
        z1, ...
        Qord.', ...
        tgrid(k), ...
        'linear', ...
        'extrap').';

    B = ...
        reshape(q,nX,3);

    dist(k) = ...
        sqrt(mean( ...
        (B*X(anchorIndex,:).' - y).^2));

end

[~,ix] = ...
    min(dist);

q = interp1( ...
    z1, ...
    Qord.', ...
    tgrid(ix), ...
    'linear', ...
    'extrap').';

pred = ...
    reshape(q,nX,3)*X.';

end


%% ========================================================================
% Diverging colour map
% =========================================================================

function cmap = blueWhiteRed(n)

anchors = [ ...
     54  94 153
    165 194 221
    247 247 247
    241 183 150
    178  55  45]/255;

cmap = interp1( ...
    linspace(-1,1,size(anchors,1)), ...
    anchors, ...
    linspace(-1,1,n), ...
    'linear');

end


%% ========================================================================
% Sequential transfer map
% =========================================================================

function cmap = transferMap(n)

anchors = [ ...
    247 251 255
    198 219 239
    107 174 214
     33 113 181
      8  48 107]/255;

cmap = interp1( ...
    linspace(0,1,size(anchors,1)), ...
    anchors, ...
    linspace(0,1,n), ...
    'linear');

end


%% ========================================================================
% Angle wrap
% =========================================================================

function a = wrapTo180Local(a)

a = ...
    mod(a+180,360)-180;

end
