function Result = Run_05_Main15dB(maxCells)
%RUN_05_MAIN15DB Formal paired R3 domain with checkpointed 25/75 replication.

root=fileparts(mfilename('fullpath'));mainDir=fileparts(root);
addpath(fullfile(root,'local_func'),'-begin');P=R3_Protocol();R3=r3_build_context(mainDir,P);
if nargin<1||isempty(maxCells),maxCells=Inf;end
calFile=fullfile(root,'output','02_reference_calibration','r3_reference_calibration_C0.mat');
thrFile=fullfile(root,'output','04_detection_threshold','detection_thresholds.mat');
if ~exist(calFile,'file'),error('r3:MissingC0','Run Run_02_FreezeReferenceCalibration first.');end
if ~exist(thrFile,'file'),error('r3:MissingThresholds','Run Run_04_CalibrateDetectionThreshold first.');end
S=load(calFile,'Result');C0=S.Result.C0;sigmaV=S.Result.sigmaV;
Q=load(thrFile,'Result');
if ~Q.Result.formal,error('r3:NonformalThresholds','Detection thresholds do not contain 500 replicates.');end
assert_protocol_compatibility(S.Result.P,P,'reference calibration');
if ~isfield(Q.Result,'P')||~strcmp(string(Q.Result.P.version),string(P.version))
    error('r3:ThresholdProtocolMismatch','Detection thresholds were not generated by the current frozen protocol.');
end
thresholds=Q.Result.Thresholds;
outDir=fullfile(root,'output','05_main_15db');if ~exist(outDir,'dir'),mkdir(outDir);end
checkpoint=fullfile(outDir,'main_detail_checkpoint.csv');
if exist(checkpoint,'file'),Detail=readtable(checkpoint,'TextType','string');else,Detail=table();end
amplitudes=[P.amplitudeNullMm P.amplitudeMainMm];cellCount=0;
for g=P.gMainMm
    for A=amplitudes
        cellCount=cellCount+1;if cellCount>maxCells,break;end
        if A==0,reps=1:P.replicateCountMaximum;else,reps=P.initialReplicateIndices;end
        Detail=run_missing(Detail,R3,C0,g,A,reps,sigmaV,thresholds,P);
        if A>0&&needs_expansion(Detail,g,A,P)
            Detail=run_missing(Detail,R3,C0,g,A,P.remainingReplicateIndices,sigmaV,thresholds,P);
        end
        writetable(Detail,checkpoint);
        fprintf('Completed g=%.3f mm, A=%.3f mm.\n',g,A);
    end
    if cellCount>=maxCells,break;end
end
[Summary,Paired]=Summarize_R3(Detail,P);
writetable(Summary,fullfile(outDir,'main_summary.csv'));
writetable(Paired,fullfile(outDir,'main_paired_summary.csv'));
Result=struct('P',P,'Detail',Detail,'Summary',Summary,'Paired',Paired,...
    'thresholds',thresholds,'sigmaV',sigmaV,'outputDir',outDir);
save(fullfile(outDir,'main_result.mat'),'Result','-v7.3');
end

function T=run_missing(T,R3,C0,g,A,reps,sigmaV,thresholds,P)
for rep=reps
    seed=P.mainHighSeeds(rep);
    if ~isempty(T)&&nnz(abs(T.g_truth_mm-g)<1e-12&T.A_true_mm==A&T.high_seed==seed)>=3,continue;end
    q=r3_fit_rows(R3,C0,g,A,P.phaseValuesRad(rep),sigmaV,seed,thresholds);
    T=[T;struct2table(q)]; %#ok<AGROW>
end
end

function tf=needs_expansion(T,g,A,P)
tf=false;names=["fixed","adaptive","state_matched"];
for name=names
    q=abs(T.g_truth_mm-g)<1e-12&T.A_true_mm==A&T.method==name;
    n=nnz(q);if n<P.replicateCountInitial,tf=true;return;end
    [lo,hi]=r3_wilson_interval(nnz(T.vib_success(q)),n,P.wilsonAlpha);
    if lo<=P.targetProbability&&hi>=P.targetProbability,tf=true;return;end
end
end

function assert_protocol_compatibility(saved,P,label)
fields={'gCalMm','gOperatingMm','gReferenceMm','mainLowSeed','referenceSnrDb'};
for i=1:numel(fields)
    f=fields{i};
    if ~isfield(saved,f)||~isequal(saved.(f),P.(f))
        error('r3:ProtocolMismatch','%s is incompatible with current protocol field %s.',label,f);
    end
end
end
