function Result = Run_05_Main15dB_Worker(workerId,cells)
%RUN_05_MAIN15DB_WORKER Run assigned R3 cells with an isolated checkpoint.

arguments
    workerId (1,1) double {mustBeInteger,mustBePositive}
    cells (:,2) double
end

root=fileparts(mfilename('fullpath'));mainDir=fileparts(root);
addpath(fullfile(root,'local_func'),'-begin');P=R3_Protocol();R3=r3_build_context(mainDir,P);
validate_cells(cells,P);
calFile=fullfile(root,'output','02_reference_calibration','r3_reference_calibration_C0.mat');
thrFile=fullfile(root,'output','04_detection_threshold','detection_thresholds.mat');
if ~exist(calFile,'file')||~exist(thrFile,'file'),error('r3:MissingPrerequisite','Run frozen calibration and threshold calibration first.');end
S=load(calFile,'Result');C0=S.Result.C0;sigmaV=S.Result.sigmaV;
Q=load(thrFile,'Result');
if ~Q.Result.formal,error('r3:NonformalThresholds','Detection thresholds do not contain 500 replicates.');end
assert_protocol_compatibility(S.Result.P,P,'reference calibration');
if ~isfield(Q.Result,'P')||~strcmp(string(Q.Result.P.version),string(P.version))
    error('r3:ThresholdProtocolMismatch','Detection thresholds were not generated by the current frozen protocol.');
end
outDir=fullfile(root,'output','05_main_15db_workers',sprintf('worker_%02d',workerId));
if ~exist(outDir,'dir'),mkdir(outDir);end
checkpoint=fullfile(outDir,'detail_checkpoint.csv');
if exist(checkpoint,'file'),Detail=readtable(checkpoint,'TextType','string');else,Detail=table();end
for i=1:size(cells,1)
    g=cells(i,1);A=cells(i,2);
    if A==0,reps=1:P.replicateCountMaximum;else,reps=P.initialReplicateIndices;end
    Detail=run_missing(Detail,R3,C0,g,A,reps,sigmaV,Q.Result.Thresholds,P);
    if A>0&&needs_expansion(Detail,g,A,P)
        Detail=run_missing(Detail,R3,C0,g,A,P.remainingReplicateIndices,sigmaV,Q.Result.Thresholds,P);
    end
    assert_complete_cell(Detail,g,A,P);
    writetable(Detail,checkpoint);
    fprintf('Worker %d completed g=%.3f mm, A=%.3f mm.\n',workerId,g,A);
end
Result=struct('P',P,'worker_id',workerId,'cells',cells,'Detail',Detail,'outputDir',outDir);
save(fullfile(outDir,'worker_result.mat'),'Result','-v7.3');
end

function T=run_missing(T,R3,C0,g,A,reps,sigmaV,thresholds,P)
for rep=reps
    seed=P.mainHighSeeds(rep);
    if ~isempty(T)&&nnz(abs(T.g_truth_mm-g)<1e-12&T.A_true_mm==A&T.high_seed==seed)>=3,continue;end
    q=r3_fit_rows(R3,C0,g,A,P.phaseValuesRad(rep),sigmaV,seed,thresholds);
    T=[T;struct2table(q)]; %#ok<AGROW>
end
end

function tf=needs_expansion(T,g,A,P)
tf=false;names=["fixed","adaptive","state_matched"];
for name=names
    q=abs(T.g_truth_mm-g)<1e-12&T.A_true_mm==A&T.method==name;n=nnz(q);
    if n<P.replicateCountInitial,tf=true;return;end
    [lo,hi]=r3_wilson_interval(nnz(T.vib_success(q)),n,P.wilsonAlpha);
    if lo<=P.targetProbability&&hi>=P.targetProbability,tf=true;return;end
end
end

function assert_complete_cell(T,g,A,P)
q=abs(T.g_truth_mm-g)<1e-12&T.A_true_mm==A;
if nnz(q)~=3*P.replicateCountMaximum,error('r3:IncompleteWorkerCell','Cell g=%.3f, A=%.3f is incomplete.',g,A);end
end

function validate_cells(cells,P)
if isempty(cells)||any(~ismembertol(cells(:,1),P.gMainMm,1e-12,'DataScale',1))||...
        any(~ismembertol(cells(:,2),[P.amplitudeNullMm P.amplitudeMainMm],1e-12,'DataScale',1))
    error('r3:InvalidWorkerCells','Each assigned cell must belong to the frozen R3 matrix.');
end
if size(unique(cells,'rows'),1)~=size(cells,1),error('r3:DuplicateWorkerCells','Worker assignment contains duplicate cells.');end
end

function assert_protocol_compatibility(saved,P,label)
fields={'gCalMm','gOperatingMm','gReferenceMm','mainLowSeed','referenceSnrDb'};
for i=1:numel(fields),f=fields{i};if ~isfield(saved,f)||~isequal(saved.(f),P.(f)),error('r3:ProtocolMismatch','%s is incompatible with current protocol field %s.',label,f);end,end
end
