%% Summarize_AdaptiveSG_Template_Comparison_20251222
clear; clc;
thisDir = fileparts(mfilename('fullpath'));
regions = ["R01", "R07", "R04"];
rows = repmat(empty_row_local(), numel(regions), 1);
for i = 1:numel(regions)
    region = regions(i);
    W = readtable(fullfile(thisDir, ...
        "AdaptiveSG_Template_Comparison_20251222_" + region + "_Window.csv"), ...
        'TextType', 'string');
    P = readtable(fullfile(thisDir, ...
        "AdaptiveSG_Template_Comparison_20251222_" + region + "_Paired.csv"), ...
        'TextType', 'string');
    current = W(W.method == "current_fixed_template", :);
    adaptive = W(W.method == "adaptive_grouped_cv_sg", :);
    assert(height(current) == height(adaptive) && height(current) == height(P), ...
        'Unpaired rows for %s.', region);
    r = empty_row_local();
    r.region = region;
    r.windowCount = height(P);
    r.selectedSgWindowMm = adaptive.selectedSgWindowMm(1);
    r.selectedSgSpanBins = adaptive.selectedSgSpanBins(1);
    r.screenSgWindowMm = adaptive.screenSgWindowMm(1);
    r.screenSgSpanBins = adaptive.screenSgSpanBins(1);
    r.finalEoChangedCount = nnz(P.currentEO ~= P.adaptiveEO);
    r.diagnosticVpTop3OrderChangedCount = nnz( ...
        current.diagnosticVpTopEO ~= adaptive.diagnosticVpTopEO);
    r.diagnosticVpTop3SetChangedCount = 0;
    for j = 1:height(current)
        c = sort(sscanf(current.diagnosticVpTopEO(j), '%f,').');
        a = sort(sscanf(adaptive.diagnosticVpTopEO(j), '%f,').');
        r.diagnosticVpTop3SetChangedCount = ...
            r.diagnosticVpTop3SetChangedCount + ~isequal(c, a);
    end
    r.currentDiagnosticVpWinnerTop1Count = nnz(current.finalDiagnosticVpRank == 1);
    r.currentDiagnosticVpWinnerTop3Count = nnz(current.finalDiagnosticVpRank <= 3);
    r.adaptiveDiagnosticVpWinnerTop1Count = nnz(adaptive.finalDiagnosticVpRank == 1);
    r.adaptiveDiagnosticVpWinnerTop3Count = nnz(adaptive.finalDiagnosticVpRank <= 3);
    r.splitDerivativeTop3OrderChangedCount = nnz( ...
        current.diagnosticVpTopEO ~= current.splitDerivativeVpTopEO);
    r.splitDerivativeTop3SetChangedCount = 0;
    for j = 1:height(current)
        c = sort(sscanf(current.diagnosticVpTopEO(j), '%f,').');
        s = sort(sscanf(current.splitDerivativeVpTopEO(j), '%f,').');
        r.splitDerivativeTop3SetChangedCount = ...
            r.splitDerivativeTop3SetChangedCount + ~isequal(c, s);
    end
    r.splitDerivativeWinnerTop1Count = nnz(current.finalSplitDerivativeVpRank == 1);
    r.splitDerivativeWinnerTop3Count = nnz(current.finalSplitDerivativeVpRank <= 3);
    r.splitDerivativeRankImprovedCount = nnz( ...
        current.finalSplitDerivativeVpRank < current.finalDiagnosticVpRank);
    r.splitDerivativeRankWorsenedCount = nnz( ...
        current.finalSplitDerivativeVpRank > current.finalDiagnosticVpRank);
    r.rmseDeltaMeanMv = mean(P.rmseDeltaMv);
    r.rmseDeltaMedianMv = median(P.rmseDeltaMv);
    r.rmseDeltaMinMv = min(P.rmseDeltaMv);
    r.rmseDeltaMaxMv = max(P.rmseDeltaMv);
    r.rmseImprovedCount = nnz(P.rmseDeltaMv < 0);
    r.currentAmplitudeStdMm = std(P.currentAmplitudeMm);
    r.adaptiveAmplitudeStdMm = std(P.adaptiveAmplitudeMm);
    r.currentAmplitudeMeanMm = mean(P.currentAmplitudeMm);
    r.adaptiveAmplitudeMeanMm = mean(P.adaptiveAmplitudeMm);
    r.amplitudeDeltaMeanMm = mean(P.amplitudeDeltaMm);
    r.amplitudeRelativeDeltaMeanPct = mean(100 .* P.amplitudeDeltaMm ./ ...
        P.currentAmplitudeMm);
    r.amplitudeDeltaMaxAbsMm = max(abs(P.amplitudeDeltaMm));
    r.amplitudeRelativeDeltaMaxAbsPct = max(abs(100 .* P.amplitudeDeltaMm ./ ...
        P.currentAmplitudeMm));
    r.amplitudeStdRatio = r.adaptiveAmplitudeStdMm / ...
        max(r.currentAmplitudeStdMm, eps);
    r.meanAbsAmplitudeDeltaMm = mean(abs(P.amplitudeDeltaMm));
    r.meanAbsDxDeltaMm = mean(abs(P.dxDeltaMm));
    r.adaptiveBoundaryHitCount = nnz(adaptive.hitBoundary);
    r.adaptiveMinQuerySafeFraction = min(adaptive.querySafeFraction);
    r.adaptiveRuntimeSec = sum(adaptive.runtimeSec);
    rows(i) = r;
end
summary = struct2table(rows);
writetable(summary, fullfile(thisDir, ...
    'AdaptiveSG_Template_RegionSummary_20251222.csv'));
disp(summary);


function row = empty_row_local()
row = struct('region', "", 'windowCount', NaN, ...
    'selectedSgWindowMm', NaN, 'selectedSgSpanBins', NaN, ...
    'screenSgWindowMm', NaN, 'screenSgSpanBins', NaN, ...
    'finalEoChangedCount', NaN, 'diagnosticVpTop3OrderChangedCount', NaN, ...
    'diagnosticVpTop3SetChangedCount', NaN, ...
    'currentDiagnosticVpWinnerTop1Count', NaN, ...
    'currentDiagnosticVpWinnerTop3Count', NaN, ...
    'adaptiveDiagnosticVpWinnerTop1Count', NaN, ...
    'adaptiveDiagnosticVpWinnerTop3Count', NaN, ...
    'splitDerivativeTop3OrderChangedCount', NaN, ...
    'splitDerivativeTop3SetChangedCount', NaN, ...
    'splitDerivativeWinnerTop1Count', NaN, ...
    'splitDerivativeWinnerTop3Count', NaN, ...
    'splitDerivativeRankImprovedCount', NaN, ...
    'splitDerivativeRankWorsenedCount', NaN, ...
    'rmseDeltaMeanMv', NaN, 'rmseDeltaMedianMv', NaN, ...
    'rmseDeltaMinMv', NaN, 'rmseDeltaMaxMv', NaN, ...
    'rmseImprovedCount', NaN, 'currentAmplitudeStdMm', NaN, ...
    'adaptiveAmplitudeStdMm', NaN, 'currentAmplitudeMeanMm', NaN, ...
    'adaptiveAmplitudeMeanMm', NaN, 'amplitudeDeltaMeanMm', NaN, ...
    'amplitudeRelativeDeltaMeanPct', NaN, 'amplitudeDeltaMaxAbsMm', NaN, ...
    'amplitudeRelativeDeltaMaxAbsPct', NaN, 'amplitudeStdRatio', NaN, ...
    'meanAbsAmplitudeDeltaMm', NaN, 'meanAbsDxDeltaMm', NaN, ...
    'adaptiveBoundaryHitCount', NaN, ...
    'adaptiveMinQuerySafeFraction', NaN, 'adaptiveRuntimeSec', NaN);
end
