function Result = Run_LowIncrementFormalSmoke()
%RUN_LOWINCREMENTFORMALSMOKE Matched low-template increment smoke test.
root=fileparts(mfilename('fullpath'));mainDir=fileparts(root);
addpath(mainDir,'-begin');addpath(fullfile(mainDir,'local_func'),'-begin');
ctx=load_inv_log_2_project_context(mainDir);tr=load_fixed_trust_domain(mainDir);
lib=make_fixed_trust_template_library(ctx.gapList,ctx.xCell,ctx.yCell,NaN,...
    ctx.cfgAna.xGridN,get_inv_log_2_model_def(),tr);
base=make_inv_log_2_demo_case(ctx,.2);cfg=base.cfgCase;
cfg.RPM_low=min(cfg.RPM_high,300);cfg.NumRevs_low=8;cfg.snrDb=20;
cfg.route30ForwardModel="low_increment";cfg.route30BaseSamples=600;
cfg.A_true=[.25 .15];cfg.f_true=[700 1200];cfg.phi_true=[pi/4 -pi/3];
gLow=.5;gHigh=.8;
lowData=simulate_low_speed_template(@(z)eval_gap_template(lib,gLow,z),...
    cfg,lib.domain,cfg.snrDb,830001);
low=build_low_speed_templates_adaptive(lowData,cfg.alpha_k,cfg.R_tip,...
    lib.domain,lib.xGrid,'cv_sg',struct());
opts=struct('xDomain',lib.domain,'fitMask',[true false false false],...
    'fitGainOffset',false);
[pathCal,~]=calibrate_low_speed_path(lib,low,opts);
pathModel=build_path_template_model(lib,low.templateLow,pathCal);
high=simulate_highspeed_from_low_increment(pathModel,gHigh-pathCal.g0,cfg,...
    cfg.snrDb,'snr_db',840001);
hm=map_highspeed_to_space(high,cfg.alpha_k,cfg.R_tip,lib.domain,.02);
ticCase=tic;fit=run_inv_log_2_low_high_main(lowData,hm,lib,cfg);elapsed=toc(ticCase);
fEst=sort(fit.f_id(:).');fTrue=sort(cfg.f_true);
Result=struct('f_true',fTrue,'f_est',fEst,'max_frequency_error',...
    max(abs(fEst-fTrue)),'g_low_true',gLow,'g_low_hat',fit.g_low_used,...
    'g_high_true',gHigh,'g_high_hat',fit.g_used,'rmse',fit.rmse,...
    'low_template_method',fit.low_speed_template_method,...
    'selected_window_mm',fit.low_speed_selected_window_mm,...
    'selected_span_bins',fit.low_speed_selected_span_bins,...
    'elapsed_s',elapsed,'success',fit.model_order==2&&...
    max(abs(fEst-fTrue))<=2&&abs(fit.g_used-gHigh)<=.05);
out=fullfile(root,'output','low_increment_formal_smoke');if~exist(out,'dir'),mkdir(out);end
T=struct2table(Result);writetable(T,fullfile(out,'low_increment_formal_smoke.csv'));
save(fullfile(out,'low_increment_formal_smoke.mat'),'Result');disp(T);
end
