function Result=Summarize_AbsoluteJointPaperMatrix(seedOffset)
%SUMMARIZE_ABSOLUTEJOINTPAPERMATRIX Combine the 10/15/20 dB main-method runs.
if nargin<1,seedOffset=0;end
root=fileparts(mfilename('fullpath'));outputRoot=fullfile(root,'output');snrList=[10 15 20];
parts=cell(numel(snrList)*numel(seedOffset),1);at=0;
for iseed=1:numel(seedOffset)
    for i=1:numel(snrList)
        folder=sprintf('structured_gap_ablation_%gdb_seed%d_absolute_method_absolute_joint',...
            snrList(i),seedOffset(iseed));
        file=fullfile(outputRoot,folder,'structured_gap_ablation.mat');
        if ~isfile(file),error('Missing paper-matrix result: %s',file);end
        data=load(file,'Audit');data.Audit.seed_offset(:)=seedOffset(iseed);
        at=at+1;parts{at}=data.Audit;
    end
end
Audit=vertcat(parts{:});modes=unique(Audit.mode,'stable');
Summary=repmat(struct('mode',"",'case_count',0,'success_count',0,'success_rate',NaN,...
    'max_frequency_error_hz',NaN,'max_gap_error_mm',NaN,...
    'max_amplitude_relative_error',NaN,'max_phase_error_rad',NaN,...
    'median_voltage_rmse',NaN,'median_elapsed_s',NaN),numel(modes)+1,1);
for i=1:numel(modes)+1
    if i<=numel(modes),q=Audit(Audit.mode==modes(i),:);label=modes(i);else,q=Audit;label="overall";end
    Summary(i)=struct('mode',label,'case_count',height(q),'success_count',nnz(q.success),...
        'success_rate',mean(q.success),'max_frequency_error_hz',max(q.frequency_error_hz),...
        'max_gap_error_mm',max(q.gap_error_mm),...
        'max_amplitude_relative_error',max(q.max_amplitude_relative_error),...
        'max_phase_error_rad',max(q.max_phase_error_rad),...
        'median_voltage_rmse',median(q.rmse),'median_elapsed_s',median(q.elapsed_s));
end
Summary=struct2table(Summary);seedTag=strjoin(string(seedOffset),'-');
SummarySNR=repmat(struct('snr_db',NaN,'case_count',0,'success_count',0,...
    'success_rate',NaN,'max_frequency_error_hz',NaN,'max_gap_error_mm',NaN,...
    'max_amplitude_relative_error',NaN,'max_phase_error_rad',NaN,...
    'median_voltage_rmse',NaN),numel(snrList),1);
for i=1:numel(snrList)
    q=Audit(Audit.snr_db==snrList(i),:);
    SummarySNR(i)=struct('snr_db',snrList(i),'case_count',height(q),...
        'success_count',nnz(q.success),'success_rate',mean(q.success),...
        'max_frequency_error_hz',max(q.frequency_error_hz),...
        'max_gap_error_mm',max(q.gap_error_mm),...
        'max_amplitude_relative_error',max(q.max_amplitude_relative_error),...
        'max_phase_error_rad',max(q.max_phase_error_rad),...
        'median_voltage_rmse',median(q.rmse));
end
SummarySNR=struct2table(SummarySNR);
out=fullfile(outputRoot,'absolute_joint_paper_matrix_seed'+seedTag);
if ~exist(out,'dir'),mkdir(out);end
writetable(Audit,fullfile(out,'absolute_joint_paper_matrix.csv'));
writetable(Summary,fullfile(out,'absolute_joint_paper_matrix_summary.csv'));
writetable(SummarySNR,fullfile(out,'absolute_joint_paper_matrix_snr_summary.csv'));
save(fullfile(out,'absolute_joint_paper_matrix.mat'),'Audit','Summary','SummarySNR');
disp(Audit);disp(Summary);disp(SummarySNR);
Result=struct('Audit',Audit,'Summary',Summary,'SummarySNR',SummarySNR,'outputDir',out);
end
