function T=Run_NoGapFinalWaveformOneSeed(seed)
if nargin<1,seed=20260406;end
root=fileparts(mfilename('fullpath'));
repo=fullfile(fileparts(fileparts(fileparts(root))),'7超高斯模型-权重-瞬态');
g=dir(fullfile(fileparts(repo),'*','main_inv_log_2_method','12_inverse_mapping_dual_frequency_validation','local')); assert(~isempty(g)); addpath(g(1).folder,'-begin');
cal=dir(fullfile(repo,'**','SGCalib_OPRCentroidRef_2sync.mat')); assert(~isempty(cal)); caseDir=cal(1).folder;
M=load(fullfile(caseDir,'BladeModel_Data.mat'),'ModelData'); C=load(fullfile(caseDir,'SGCalib_OPRCentroidRef_2sync.mat'),'Calib'); ModelData=M.ModelData; Calib=C.Calib;
snrs=[5 10 15 20]; cases=[500 1300;500 560;700 1200;900 1400]; A=[.25 .15]; ph=[pi/4 -pi/6]; alpha=[.9599 2.0378 3.1158]; opr=10; rpm=3000; fs=2e6; nrev=4; R=62; grid=(300:20:1500).'; K=[10 8 6 5];
p=ModelData.pA; G=ModelData.G; xx=linspace(-50,50,1000); yy=apkm(p,xx+G.center_fixed,G); p(2)=p(2)*(3-.12)/(max(yy)-min(yy)); p(1)=.12;
rows=repmat(row0(),0,1);
for is=1:numel(snrs), for ic=1:size(cases,1)
 ftrue=cases(ic,:); snr=snrs(is); [t,V,sid]=observe(p,G,ftrue,A,ph,snr,nrev,rpm,fs,R,alpha,opr,seed); d=struct('t',t,'V_cap',V,'R_tip',R,'rpm',rpm,'fs',fs,'opr_angle_rad',deg2rad(opr)); inv=inverse_pass(d,Calib,nrev,alpha,4); ok=inv.valid&inv.weight>0; cfg=struct('dualInverseTopK',K(is),'dualInverseScanTargetSamples',5000); [cs,meta]=scan_dual_inverse_frequency_pairs(inv.t(ok),inv.u_inv(ok),inv.weight(ok),grid,cfg); rr=repmat(row0(),0,1);
 for j=1:numel(cs), fsd=cs(j).f; p0=[A(1) ph(1) A(2) ph(2) fsd]; lb=[0 -pi 0 -pi max(50,fsd-250)]; ub=[1 pi 1 pi min(1600,fsd+250)]; obj=@(q)sum((V-wave(q,t,sid,p,G,alpha,opr,rpm,R)).^2); o=optimoptions('fmincon','Display','off','Algorithm','sqp','MaxIterations',160,'MaxFunctionEvaluations',3000); [q,fv,ef]=fmincon(obj,p0,[],[],[],[],lb,ub,[],o); if q(5)>q(6), q=[q(3) q(4) q(1) q(2) q(6) q(5)]; end; ut=A(1)*sin(2*pi*ftrue(1)*t+ph(1))+A(2)*sin(2*pi*ftrue(2)*t+ph(2)); uf=q(1)*sin(2*pi*q(5)*t+q(2))+q(3)*sin(2*pi*q(6)*t+q(4)); z=row0(); z.snr_db=snr; z.f1_true=ftrue(1); z.f2_true=ftrue(2); z.candidate_rank=j; z.f1_seed=fsd(1); z.f2_seed=fsd(2); z.f1_est=q(5); z.f2_est=q(6); z.A1_est=q(1); z.A2_est=q(3); z.phi1_est=q(2); z.phi2_est=q(4); z.f_err_hz=max(abs(sort(q([5 6]))-sort(ftrue))); z.A_err_pct=max(abs(sort(q([1 3]))-sort(A)./sort(A)*100)); z.u_rmse=sqrt(mean((ut-uf).^2)); z.v_rmse=sqrt(fv/numel(V)); z.exitflag=ef; rr(end+1)=z; end
 [~,b]=min([rr.v_rmse]); z=rr(b); z.candidate_count=meta.candidate_count; z.selected_topk=K(is); z.true_candidate_rank=find(arrayfun(@(x)all(abs(x.f-ftrue)<21),cs),1); z.final_rank=b; z.final_is_true=z.f_err_hz<5; rows(end+1)=z; fprintf('SNR %g [%g %g] Top-%d truth-rank %g final-rank %d fErr %.4g\n',snr,ftrue(1),ftrue(2),K(is),z.true_candidate_rank,b,z.f_err_hz);
end,end
T=struct2table(rows);T.seed=repmat(seed,height(T),1);out=fullfile(root,'output','no_gap_condition_comparison');if ~exist(out,'dir'),mkdir(out);end;writetable(T,fullfile(out,sprintf('no_gap_seed_%d.csv',seed)));disp(T);
end
function r=row0(); r=struct('snr_db',NaN,'f1_true',NaN,'f2_true',NaN,'candidate_rank',NaN,'candidate_count',NaN,'selected_topk',NaN,'true_candidate_rank',NaN,'final_rank',NaN,'final_is_true',false,'f1_seed',NaN,'f2_seed',NaN,'f1_est',NaN,'f2_est',NaN,'A1_est',NaN,'A2_est',NaN,'phi1_est',NaN,'phi2_est',NaN,'f_err_hz',NaN,'A_err_pct',NaN,'u_rmse',NaN,'v_rmse',NaN,'exitflag',NaN); end
function [t,V,sid]=observe(p,G,f,A,ph,snr,nrev,rpm,fs,R,alpha,opr,seed); om=rpm*2*pi/60; tt=(0:1/fs:nrev*60/rpm)'; u=A(1)*sin(2*pi*f(1)*tt+ph(1))+A(2)*sin(2*pi*f(2)*tt+ph(2)); t=[];V=[];sid=[]; base=p(1); for m=0:nrev-1, top=deg2rad(opr)/om+m*60/rpm; for k=1:numel(alpha), te=top+alpha(k)/om; ix=find(abs(tt-te)<=11/(R*om)); x=R*om*(tt(ix)-te)-u(ix); vk=base*ones(size(ix)); on=abs(x)<20; vk(on)=apkm(p,x(on)+G.center_fixed,G); t=[t;tt(ix)];V=[V;vk];sid=[sid;k*ones(numel(ix),1)]; end,end; rng(seed,'twister'); ns=sqrt(var(V,1)/10^(snr/10)); n=randn(size(V)); V=V+ns*(n-mean(n))/std(n,1); end
function V=wave(q,t,sid,p,G,alpha,opr,rpm,R); om=rpm*2*pi/60; u=q(1)*sin(2*pi*q(5)*t+q(2))+q(3)*sin(2*pi*q(6)*t+q(4)); V=zeros(size(t)); for k=1:numel(alpha), ix=sid==k; te=deg2rad(opr)/om+alpha(k)/om+floor(t(ix)/(60/rpm))*(60/rpm); x=R*om*(t(ix)-te)-u(ix); v=p(1)*ones(sum(ix),1); on=abs(x)<20; v(on)=apkm(p,x(on)+G.center_fixed,G); V(ix)=v; end,end
function y=apkm(p,x,G); x=x-G.center_fixed;r=p(3);w=p(4);lo=max(x-w/2,-r);hi=min(x+w/2,r);S=max(0,Fint(hi,r)-Fint(lo,r));L=max(1e-6,r+.5*w);z=x./L;b=p(5:end);y=p(1)+p(2)*(S./G.d0_fixed).*(1+b(1)*z+b(2)*z.^2+b(3)*z.^3);end
function a=Fint(t,r);t=max(-r,min(r,t));a=t.*sqrt(max(0,r.^2-t.^2))+r.^2.*asin(t./r);end
function inv=inverse_pass(d,C,nrev,alpha,dec);om=d.rpm*2*pi/60;per=60/d.rpm; ta=[];ua=[];wa=[];va=[]; for m=0:nrev-1, to=d.opr_angle_rad/om+m*per; for k=1:numel(alpha), sc=C.Sensor(k);te=to+alpha(k)/om; ix=find(abs(d.t-te)<=min(sc.dx_trust_left,sc.dx_trust_right)/(d.R_tip*om)); if numel(ix)<15,continue;end;t=d.t(ix);x=d.R_tip*om*(t-te);v=max(d.V_cap(ix)-C.V_base,0);v=smooth_segment(movmedian(v,11,'Endpoints','shrink'),61,3); B=sc.B; xi=sign((1:numel(v))'-find(v==max(v),1)).*sc.w.*(-log(max(.05*B,min(B-1e-4,v))/B)).^(1/sc.n); keep=1:dec:numel(ix);ta=[ta;t(keep)];ua=[ua;x(keep)-xi(keep)];e=abs(gradient(v));wa=[wa;.05+.95*e(keep)/(max(e)+eps)];va=[va;isfinite(xi(keep))];end,end;inv=struct('t',ta,'u_inv',ua,'weight',wa,'valid',va);end
function y=smooth_segment(x,w,d);w=min(w,numel(x)-mod(numel(x)+1,2));if w<d+2,y=x;return;end;if mod(w,2)==0,w=w-1;end;if exist('sgolayfilt','file')==2,y=sgolayfilt(x,d,w);else,y=movmean(x,w,'Endpoints','shrink');end;y=max(y,0);end
