function cfg = BTTDataConfig_20251222()
%BTTDATACONFIG_20251222 Package-local data facts for Foundation.
P = Config_20251222();
cfg = struct();
cfg.dataset = P.dataset;
cfg.route_dir = P.paths.root;
cfg.validation_root = fileparts(P.paths.root);
cfg.dataset_root = P.paths.rawDatasetRoot;
cfg.low_speed_case = P.case.lowSpeedCase;
cfg.dynamic_cases = {P.case.dynamicCase};
cfg.strain_root = P.paths.strainRoot;
cfg.output_root = P.paths.preparedFoundation;
cfg.step01_output_dir = fullfile(cfg.output_root, 'step01_low_speed_reference');
cfg.step02_output_dir = fullfile(cfg.output_root, 'step02_dynamic_btt');
cfg.step03_output_dir = fullfile(cfg.output_root, 'step03_observation_bundle');
cfg.step04_output_dir = fullfile(cfg.output_root, 'step04_low_speed_template');
cfg.opr_slot_calibration_file = P.files.oprSlotCalibration;
cfg.figure_root = fullfile(P.paths.figures, 'foundation');
cfg.save_figures = P.run.saveFigures;
cfg.candidate_sensor_ids = P.case.analysisSensors;
cfg.sensor_ids = P.case.analysisSensors;
cfg.btt_channel_ids = cfg.sensor_ids;
cfg.optical_fiber_ids = [];
cfg.fiber_sensor_ids = [];
cfg.btt_reference_sensor_type = 'file_channel';
cfg.capacitance_ids = cfg.sensor_ids;
cfg.eddy_current_ids = [];
cfg.strain_channel_ids = [];
cfg.unused_ids = [5 6 7 8];
cfg.opr_id = 4;
cfg.blades_num = P.machine.bladeCount;
cfg.opr_timing_reference = 'rising_edge';
cfg.opr_reference_time_column = 'opr_start_time_s';
cfg.opr_timing_method = 'threshold_rising_edge';
cfg.standard_angle_reference_field = 'Standard_Relative_Angles_StartEdge';
cfg.standard_angle_reference_name = 'opr_threshold_start_edge';
cfg.step04_standard_angle_source = 'startedge';
cfg.opr_events_per_revolution = P.machine.oprPulsesPerRevolution;
cfg.opr_events_per_revolution_policy = 'fixed_known_from_experiment';
cfg.step04_opr_events_per_revolution = cfg.opr_events_per_revolution;
cfg.step04_opr_events_per_revolution_policy = cfg.opr_events_per_revolution_policy;
cfg.opr_angle_map_mode = 'adjacent_opr_unequal_slotcal_startedge';
cfg.sample_rate_hz = P.machine.sampleRateHz;
cfg.pinlv = cfg.sample_rate_hz;
cfg.r_tip_mm = P.machine.tipRadiusMm;
cfg.initial_trim_points = 20000;
cfg.gap_points = 1000;
cfg.opr_threshold = 1.5;
cfg.sensor_threshold_default = 0.5;
cfg.reference_sensor_id = 1;
cfg.reference_search_revs = 3;
cfg.max_alignment_search_starts = 24;
cfg.max_laps_process = 5000;
cfg.sensor_thresholds = containers.Map('KeyType','double','ValueType','double');
for sid = cfg.sensor_ids
    cfg.sensor_thresholds(sid) = cfg.sensor_threshold_default;
end
end
