clc; close all;

%CALIBRATE_STEP05_JOINTSTATICETA_FROMPREVIEW_20250527
% Diagnostic only: estimate a fixed residual eta_s from saved NoEta Step05
% preview bundles, then compare it with free window eta and Step04 xc.

this_dir = fileparts(mfilename('fullpath'));
addpath(fileparts(this_dir));

noeta_file = fullfile(this_dir, 'output', ...
    'step05_single_sync_direct_template_eta_none', ...
    '20250526_2500-3500_t400', ...
    'Result_Step05_SingleSyncDirectTemplate_B1_S136_20250527.mat');

free_eta_file = fullfile(this_dir, 'output', ...
    'step05_single_sync_direct_template_eta_window_bounded', ...
    '20250526_2500-3500_t400', ...
    'Result_Step05_SingleSyncDirectTemplate_B1_S136_20250527.mat');

template_file = fullfile(this_dir, 'output', ...
    'step04_low_speed_template', ...
    'Template_OPRCenterStd_LowSpeed_AllBlades_S136_20250527.mat');

out_dir = fullfile(this_dir, 'output', ...
    'step05_joint_static_eta_preview');

Summary = Calibrate_Step05_JointStaticEta_FromPreview(this_dir, ...
    'NoEtaResultFile', noeta_file, ...
    'FreeEtaResultFile', free_eta_file, ...
    'Step04TemplateFile', template_file, ...
    'OutputDir', out_dir, ...
    'GradientMinRatio', 0.08, ...
    'QAbsLimitMm', 1.50, ...
    'HuberIterations', 4, ...
    'MinWindows', 3, ...
    'MinPointsPerSensorWindow', 60, ...
    'Verbose', true);

