function models = R5_Build_SensorConditionedDynamicModels_20251222(sidecarFile, templateFile, targetBlade)
%R5_BUILD_SENSORCONDITIONEDDYNAMICMODELS_20251222
% Adapt the frozen R4/Main10-compatible library to the common R5 model API.
% Only the scalar sensor-wise dynamic gap increment is exposed.

cfg = Config_20251222();
if nargin < 1 || isempty(sidecarFile)
    error('R5:MissingSidecar','A frozen R4-compatible sidecar is required.');
end
if nargin < 2 || isempty(templateFile)
    templateFile = cfg.files.lowSpeedTemplate;
end
if nargin < 3 || isempty(targetBlade)
    targetBlade = cfg.case.targetBlade;
end

S = load(R5_StageMatForMatlab(sidecarFile,'r5_sidecar'), 'SensorConditionedLibrary');
T = load(R5_StageMatForMatlab(templateFile,'r5_template'), 'Template');
assert(isfield(S,'SensorConditionedLibrary'), ...
    'R5:SidecarSchema','Sidecar must contain SensorConditionedLibrary.');
L = S.SensorConditionedLibrary;
assert(strcmpi(L.schema,'R5_SENSOR_CONDITIONED_SIDECAR_V1') && ...
    strcmpi(L.latent_mode,'sensor_conditioned'), ...
    'R5:SidecarSchema','Unexpected sensor-conditioned sidecar schema.');
assert(isfield(L,'staticTiltCarrier') && isfield(L,'staticTiltFrozen') && ...
    isfield(L,'spaceGapSlopeUsed') && isfield(L,'allowDynamicTilt'), ...
    'R5:StaticTiltContract','Sidecar lacks the static tilt contract.');
assert(strcmpi(L.staticTiltCarrier,'explicit_profile') && ...
    logical(L.staticTiltFrozen) && logical(L.spaceGapSlopeUsed) && ...
    ~logical(L.allowDynamicTilt), 'R5:StaticTiltContract', ...
    'Static tilt ownership is not verified or dynamic tilt is enabled.');
% The sidecar state is already the localized static response state.  Do not
% reconstruct a spatial tilt from the audit-only mu/tau values during fitting.
R = struct('coeff',double(L.response_coeff), ...
    'xGrid',double(L.x_mm(:)),'gTrainMm',double(L.gap_mm(:)), ...
    'g0Mm',double(L.gref_mm));
assert(size(R.coeff,1)==numel(R.xGrid) && size(R.coeff,2)==3, ...
    'R5:SidecarSchema','Sidecar response coefficient dimensions are invalid.');

ids = double(cfg.case.analysisSensors(:).');
gapIds = double(cfg.case.gapSensors(:).');
sidecarIds = double([L.sensor.sensor_id]);
assert(isequal(sort(unique(sidecarIds)),sort(unique(ids))), ...
    'R5:SensorSetMismatch', ...
    'Sidecar sensor IDs must exactly match cfg.case.analysisSensors.');
assert(isfield(L,'target_blade') && double(L.target_blade)==double(targetBlade), ...
    'R5:SidecarTargetMismatch', ...
    'Sidecar target_blade does not match the requested target blade.');
models = struct('sensorId',{},'bladeId',{},'gapReferenceMm',{},'latent',{}, ...
    'isGapSensor',{},'templateDomainMm',{},'responseDomainMm',{},'templateVoltageUnit',{}, ...
    'coord',{},'gapDomainMm',{},'templateEvaluate',{},'evaluate',{});

for sid = ids
    ic = find(arrayfun(@(s) double(s.sensor_id)==sid, L.sensor),1);
    assert(~isempty(ic),'R5:SensorMissing','Sidecar lacks sensor %d.',sid);
    it = find([T.Template.SensorBlade.sensor_id]==sid & ...
        [T.Template.SensorBlade.blade_id]==targetBlade,1);
    assert(~isempty(it),'R5:TemplateMissing','Template lacks B%d/S%d.',targetBlade,sid);
    entry = L.sensor(ic);
    assert(isfield(entry,'registration') && isfield(entry,'state'), ...
        'R5:SidecarSchema','Sidecar sensor %d lacks registration or state.',sid);
    sc = struct('xScale',double(entry.registration.x_scale), ...
        'tauMm',double(entry.registration.tau_mm), ...
        'voltageGain',double(entry.registration.voltage_gain), ...
        'voltageOffsetMv',double(entry.registration.voltage_offset_mv), ...
        'g0Mm',double(entry.state.gap_mm), ...
        'muGapPerXMm',double(entry.state.mu_gap_per_x_mm));
    assert(double(entry.state.blade_id)==double(targetBlade), ...
        'R5:SidecarTargetMismatch', ...
        'Sidecar sensor %d is not bound to target blade B%d.',sid,targetBlade);
    tpl = T.Template.SensorBlade(it);
    isGap = ismember(sid,gapIds);
    if isGap
        assert(isfinite(sc.g0Mm),'R5:GapReferenceMissing','Missing g0 for S%d.',sid);
        evalFcn = @(dg,xq) eval_gap(sc,R,tpl,dg,xq);
        gapRef = double(sc.g0Mm);
        gapDomain = [min(double(R.gTrainMm(:))) max(double(R.gTrainMm(:)))];
    else
        evalFcn = @(dg,xq) eval_direct(tpl,xq);
        gapRef = NaN;
        gapDomain = [NaN NaN];
    end
    reg = struct('responseScale',double(sc.xScale), ...
        'responseTauMm',double(sc.tauMm), ...
        'responseOffsetMm',0);
    models(end+1) = struct('sensorId',sid,'bladeId',targetBlade, ...
        'gapReferenceMm',gapRef,'latent',NaN,'isGapSensor',isGap, ...
        'templateDomainMm',[min(double(tpl.x_grid(:))) max(double(tpl.x_grid(:)))], ...
        'responseDomainMm',[min(double(R.xGrid(:))) max(double(R.xGrid(:)))], ...
        'templateVoltageUnit','V','coord',reg,'gapDomainMm',gapDomain, ...
        'templateEvaluate',@(xq) interp1(double(tpl.x_grid(:)), ...
            double(tpl.v_grid(:))*1000,min(max(double(xq(:)), ...
            min(double(tpl.x_grid(:)))),max(double(tpl.x_grid(:)))), ...
            'pchip',NaN),'evaluate',evalFcn); %#ok<AGROW>
end
end

function [y,info] = eval_gap(sc,R,tpl,dg,xq,useSlope)
xq = double(xq(:)); dg = double(dg);
assert(isscalar(dg),'R5:ScalarDg');
% The localized static response state already carries the static geometry,
% including any apparent spatial tilt.  Dynamic evaluation changes only the
% scalar clearance increment and never reconstructs mu_s*(x-tau_s).
xGrid = double(R.xGrid(:));
gGrid = double(R.gTrainMm(:));
xOffset = 0;
xResponse = xq-xOffset;
xF = double(sc.xScale).*(xResponse-double(sc.tauMm));
tx = double(tpl.x_grid(:));
yL = interp1(tx,double(tpl.v_grid(:))*1000, ...
    min(max(xResponse,min(tx)),max(tx)),'pchip',NaN);
gLow = repmat(double(sc.g0Mm),size(xq));
gHigh = gLow+dg;
g0 = min(max(gLow,min(gGrid)),max(gGrid));
g1 = min(max(gHigh,min(gGrid)),max(gGrid));
f0 = eval_surface(R.coeff,xGrid,double(R.g0Mm),g0,xF);
f1 = eval_surface(R.coeff,xGrid,double(R.g0Mm),g1,xF);
y = yL+double(sc.voltageGain).*(f1-f0);
info = struct('xQuery',xq,'xRegistered',xF,'gapLowMm',gLow, ...
    'gapHighMm',gHigh,'gapClippedMm',g1, ...
    'overshootGapMm',max(min(gGrid)-gHigh,0)+max(gHigh-max(gGrid),0), ...
    'overshootXmm',max(min(tx)-xResponse,0)+max(xResponse-max(tx),0), ...
    'overshootResponseXmm',max(min(xGrid)-xF,0)+max(xF-max(xGrid),0), ...
    'noGapMv',yL,'gapIncrementMv',y-yL);
end

function [y,info] = eval_direct(tpl,xq)
xq = double(xq(:)); xg = double(tpl.x_grid(:));
y = interp1(xg,double(tpl.v_grid(:))*1000, ...
    min(max(xq,min(xg)),max(xg)),'pchip',NaN);
info = struct('xQuery',xq,'xRegistered',xq,'gapLowMm',NaN(size(xq)), ...
    'gapHighMm',NaN(size(xq)),'gapClippedMm',NaN(size(xq)), ...
    'overshootGapMm',zeros(size(xq)), ...
    'overshootXmm',max(min(xg)-xq,0)+max(xq-max(xg),0), ...
    'noGapMv',y,'gapIncrementMv',zeros(size(y)));
end

function y = eval_surface(B,xGrid,gref,g,xq)
xq = double(xq(:)); g = double(g(:));
if isscalar(g), g = repmat(g,size(xq)); end
xq = min(max(xq,min(xGrid)),max(xGrid));
v = zeros(size(xq));
for k=1:3
    bk = interp1(xGrid,double(B(:,k)),xq,'linear',NaN);
    if k==1, v=v+bk;
    elseif k==2, v=v+bk./g;
    else, v=v+bk.*log(g/gref);
    end
end
y=v;
end