function outputFile = R5_Export_SensorConditionedSidecar_20251222(r4LibraryFile, outputFile, targetBlade)
%R5_EXPORT_SENSORCONDITIONEDSIDECAR_20251222
% Convert the frozen R4/Main10-compatible static library into the common
% R5 sensor-conditioned sidecar schema. No dynamic fit or validation data is
% used here; each sensor receives one frozen target-blade static state.

if nargin < 1 || isempty(r4LibraryFile)
    error('R5:MissingR4Library','An R4-compatible library is required.');
end
if nargin < 3 || isempty(targetBlade), targetBlade = 1; end
if nargin < 2 || isempty(outputFile)
    outputFile = fullfile(fileparts(r4LibraryFile), ...
        sprintf('R5_SensorConditionedSidecar_B%d_S123.mat',targetBlade));
end

S = load(r4LibraryFile,'CorrectedGapLibrary');
C = S.CorrectedGapLibrary;
assert(isstruct(C) && isfield(C,'responseSurface') && ...
    isfield(C.responseSurface,'coeff'), ...
    'R5:R4LibrarySchema','R4 library lacks response-surface coefficients.');
assert(isfield(C,'sensor'), ...
    'R5:R4LibrarySchema','R4 library lacks sensor calibration states.');
sensorStates = C.sensor;
assert(isstruct(sensorStates) && ~isempty(sensorStates), ...
    'R5:R4LibrarySchema','R4 sensor calibration states are empty or invalid.');
R = C.responseSurface;
x = double(R.xGrid(:));
g = double(R.gTrainMm(:));
gref = double(R.g0Mm);
B = double(R.coeff);
assert(size(B,1)==numel(x) && size(B,2)==3, ...
    'R5:R4LibraryShape','R4 coefficient shape is not [numel(x),3].');

L = struct('schema','R5_SENSOR_CONDITIONED_SIDECAR_V1', ...
    'latent_mode','sensor_conditioned','x_mm',x,'gap_mm',g, ...
    'gref_mm',gref,'response_coeff',B, ...
    'source_r4_library',r4LibraryFile, ...
    'target_blade',double(C.targetBlade), ...
    'staticModel','frozen_explicit_gap_profile', ...
    'staticTiltCarrier','explicit_profile', ...
    'staticTiltSource','low_speed_sensor_conditioned_calibration', ...
    'staticTiltFrozen',true,'spaceGapSlopeUsed',true, ...
    'allowDynamicTilt',false, ...
    'extrapolationAllowed',false, ...
    'sensor',struct('sensor_id',{},'registration',{},'state',{},'coeff_by_state',{}));
for k = 1:numel(sensorStates)
    sc = sensorStates(k);
    assert(isfield(sc,'sensorId') && isfield(sc,'xScale') && ...
        isfield(sc,'tauMm') && isfield(sc,'voltageGain') && ...
        isfield(sc,'voltageOffsetMv') && isfield(sc,'g0Mm') && ...
        isfield(sc,'lowFitRmseMv'), ...
        'R5:R4LibrarySchema', ...
        'R4 sensor %d lacks a required calibration field.',k);
    sid = double(sc.sensorId);
    reg = struct('x_scale',double(sc.xScale),'tau_mm',double(sc.tauMm), ...
        'voltage_gain',double(sc.voltageGain),'voltage_offset_mv', ...
        double(sc.voltageOffsetMv),'target_x_offset_mm',0);
    st = struct('blade_id',double(targetBlade),'z',NaN, ...
        'gap_mm',double(sc.g0Mm),'rmse_mv',double(sc.lowFitRmseMv), ...
        'B',B,'mu_gap_per_x_mm',double(sc.muGapPerXMm), ...
        'gap_tau_mm',double(sc.tauMm), ...
        'target_x_offset_mm',0);
    sensorEntry = struct('sensor_id',sid,'registration',reg, ...
        'state',st,'coeff_by_state',{{B}});
    L.sensor(k) = sensorEntry;
end
SensorConditionedLibrary = L; %#ok<NASGU>
if ~exist(fileparts(outputFile),'dir'), mkdir(fileparts(outputFile)); end
save(outputFile,'SensorConditionedLibrary','-v7.3');
end